### ISSUE TITLE
error on run

### ISSUE THREAD

**Issue by sami8github** [ChrisDill/Raylib-cs#1]
Hi
sorry this is not an issue but I dont know how to send you a message , please help me
I downloaded Raylib and I instaled it , then I downloaded this project and compiled it
I got an error :
System.DllNotFoundException: 'Unable to load DLL 'raylib': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'
how to run this project ? do I need to compile Raylib to run it whith c# ? ,how to do so ? how to get dlls files and how to add and use them with the project ?
I want to run Raylib inside winform application , how to make viewport display on a panel or form for example ?
Please help me ,Thank You very Much

**Comment by ChrisDill** [comment]
Hi
I have only just set this up to see how well it works in C#.
You need the compiled DLL of raylib in the same directory as the .exe.  I have added the DLL I am using to the project, just copy it to the output.
I am not sure how to run a raylib window inside windows forms but I will add it as a feature.

**Comment by sami8github** [comment]
Hi
I hope you can help me, thank you very much
I want to make an editor with gui in c# using raylib, I found this binding project and I decided to use it , I need to compile Raylib as x86 dll, and I want to know how to compile Raylib for windows x86 and x64 using mingw?
I installed mingw an I set the environment path
please explain how to build raylib using mingw32-make and how to get compiled raylib dlls ?
https://github.com/raysan5/raylib/wiki/Working-on-Windows
how to pass parameters like opengl version and other parameters?
how to pass parameters like in that page:
https://github.com/raysan5/raylib/wiki/CMake-Build-Options

I tried to build with mingw and I got error:

```
> C:\raylib\raylib\src>mingw32-make PLATFORM=PLATFORM_DESKTOP
> ar rcs ../release/libs/win32/mingw32/libraylib.a core.o shapes.o textures.o text.o models.o utils.o rglfw.o audio.o stb_vorbis.o mini_al.o
> ar: ../release/libs/win32/mingw32/libraylib.a: No such file or directory
> Makefile:518: recipe for target 'raylib' failed
> mingw32-make: *** [raylib] Error 1
```

I understand that to build raylib for desktop I must run the command : mingw32-make PLATFORM=PLATFORM_DESKTOP
the parameter PLATFORM mean that it can compile to linux and others :
why is needed to compile raylib source (not a game) to android ?

how to compile a game with mingw32-make ?
Q : when compile a game with mingw32-make does this include raylib dlls inside the builded exe ? I mean is all raylib .h .c files compiled inside the game ? is it no need to copy raylib dlls with game.exe ?
how to compile a game using mingw for other platforms like android and web and how to set openglES version 1.1 or 2.2 or 3 ?
I hope that you can help me , Thank You Very Much

**Comment by ChrisDill** [comment]
For this project im using the visual studio 2017 project that comes with raylib in C:\raylib\raylib\projects to build the x86/64 dlls. Im sure on how to build it using mingw correctly.

Regenerate bindings is what generates the C# file not the dll itself.

**Comment by sami8github** [comment]
Thank you bro
I compiled with visual studio and I get the dll thank you

**Comment by sami8github** [comment]
ok after long search I found the folowing:
1-dll file produced with visual studio codeblocs..
2-building raylib with mingw must create this dir manualy:
\release\libs\win32\mingw32
change project name and projet files list in the makefile ,(get the makefile from C:\raylib\raylib\templates\standard_game) and copy it to your game.c dir and change it.

still dont know how to build x86 & x64 dll with mingw

**Comment by ChrisDill** [comment]
Hi, the library has changed alot since this issue opened. Did you get it to compile? 
The project is currently a custom build of raylib so I can access all the features.

**Comment by sami8github** [comment]
Very nice bro, this is great news
I stopped on compiling to other platforms especially android.

**Comment by nurrr001** [comment]
pls help fix this
 *  Executing task: C/C++: gcc.exe build active file 

Starting build...
cmd /c chcp 65001>nul && C:\raylib\w64devkit\bin\gcc.exe -fdiagnostics-color=always -g "G:\Nur's folder\coding\c++\Raylib\Raylib-CPP-Starter-Template-for-VSCODE-V2-main\Raylib-CPP-Starter-Template-for-VSCODE-V2-main\src\main.cpp" -o "G:\Nur's folder\coding\c++\Raylib\Raylib-CPP-Starter-Template-for-VSCODE-V2-main\Raylib-CPP-Starter-Template-for-VSCODE-V2-main\src\main.exe"
C:\raylib\w64devkit\bin/ld.exe: C:\Users\pikxa\AppData\Local\Temp\ccCqsJsf.o: in function `main':
G:/Nur's folder/coding/c++/Raylib/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/src/main.cpp:11: undefined reference to `Ball::Ball()'
C:\raylib\w64devkit\bin/ld.exe: G:/Nur's folder/coding/c++/Raylib/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/src/main.cpp:13: undefined reference to `InitWindow'
C:\raylib\w64devkit\bin/ld.exe: G:/Nur's folder/coding/c++/Raylib/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/src/main.cpp:14: undefined reference to `SetTargetFPS'
C:\raylib\w64devkit\bin/ld.exe: G:/Nur's folder/coding/c++/Raylib/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/src/main.cpp:18: undefined reference to `BeginDrawing'
C:\raylib\w64devkit\bin/ld.exe: G:/Nur's folder/coding/c++/Raylib/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/src/main.cpp:19: undefined reference to `ClearBackground'
C:\raylib\w64devkit\bin/ld.exe: G:/Nur's folder/coding/c++/Raylib/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/src/main.cpp:20: undefined reference to `Ball::Update()'
C:\raylib\w64devkit\bin/ld.exe: G:/Nur's folder/coding/c++/Raylib/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/src/main.cpp:21: undefined reference to `Ball::Draw()'
C:\raylib\w64devkit\bin/ld.exe: G:/Nur's folder/coding/c++/Raylib/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/src/main.cpp:22: undefined reference to `EndDrawing'
C:\raylib\w64devkit\bin/ld.exe: G:/Nur's folder/coding/c++/Raylib/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/src/main.cpp:16: undefined reference to `WindowShouldClose'
collect2.exe: error: ld returned 1 exit status

Build finished with error(s).

 *  The terminal process failed to launch (exit code: -1). 
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: C:/raylib/w64devkit/bin/mingw32-make.exe RAYLIB_PATH=C:/raylib/raylib PROJECT_NAME=main OBJS=*.cpp BUILD_MODE=DEBUG 

mingw32-make main
make[1]: Entering directory 'G:/Nur's folder/coding/c++/Raylib/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/Raylib-CPP-Starter-Template-for-VSCODE-V2-main'
make[1]: *** No rule to make target '*.cpp', needed by 'main'.  Stop.
make[1]: Leaving directory 'G:/Nur's folder/coding/c++/Raylib/Raylib-CPP-Starter-Template-for-VSCODE-V2-main/Raylib-CPP-Starter-Template-for-VSCODE-V2-main'
make: *** [Makefile:387: all] Error 2

 *  The terminal process "C:\raylib\w64devkit\bin\mingw32-make.exe 'RAYLIB_PATH=C:/raylib/raylib', 'PROJECT_NAME=main', 'OBJS=*.cpp', 'BUILD_MODE=DEBUG'" terminated with exit code: 2. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by 9ParsonsB** [comment]
@nurrr001 This does not seem related to raylib-cs
