### ISSUE TITLE
Can't figure out how to set up a project

### ISSUE THREAD

**Issue by RrayAgent** [ChrisDill/Raylib-cs#101]
I have no idea how to get it set up in a project, I've over the read me and watched videos on how to set it up and it just doesn't work for me. However I am using VS 2022, so I don't know if the problem is there (or I could just be stupid and missing something).

**Comment by CastimierDev** [comment]
@RrayAgent I just make a console app and use nuget to add raylib, try that and if you have any problems you can send me a message

**Comment by RrayAgent** [comment]
Yeah I actually figured that out a while ago, and then forgot to just kind of close this. I'm very sorry for taking up your time.
