### ISSUE TITLE
The function GetImageColor() doesn't exist

### ISSUE THREAD

**Issue by Samstroyer** [ChrisDill/Raylib-cs#102]
Before submitting a new issue, please verify and check:

 - [x] The issue is specific to Raylib-cs and not raylib
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of Raylib-cs

### Issue description

The function Raylib.GetImageColor(); That is supposed to take in an image for argument and return a color[] doesn't exist. !!It is mentioned in the Raylib CheatSheet.!!

### Environment

*Provide your Platform, Operating System, OpenGL version, GPU details where you experienced the issue.*
Windows 10, Visual Studio Code

### Issue screenshot

![image](https://user-images.githubusercontent.com/90481817/150126989-3a49ba71-90c6-4b19-8546-6457b1bfb863.png)
![image](https://user-images.githubusercontent.com/90481817/150127233-90edfb4b-8a8e-449f-9bb1-3e5c55074ff7.png)

### Code example

//Lazy example
using Raylib_cs;
Image img = Raylib.LoadImage(**PATH**);
Color c = Raylib.GetImageColor(img, 0, 0);

**Comment by 9ParsonsB** [comment]
`GetImageColor` was added in raylib 4.0.0. Raylib-cs currently only supports up to 3.7.0. 

There is a 4.0 branch, PR (#100), & pre-release NuGet packages, if you'd like to try it out early. We are using this major version bump to make some big internal changes.
