### ISSUE TITLE
Unable to find an entry point named 'DrawTextRec' in shared library 'raylib'.

### ISSUE THREAD

**Issue by acheddadi** [ChrisDill/Raylib-cs#103]
As the title says, I am not able to call the function DrawTextRec(). Everything else seems to work fine.

**Comment by 9ParsonsB** [comment]
What version of `Raylib-cs` are you using?

**Comment by acheddadi** [comment]
> What version of `Raylib-cs` are you using?

Hello, I am using 3.7.0.1.

**Comment by 9ParsonsB** [comment]
How did you install `Raylib-cs` and what version of  `raylib`  are you using?

**Comment by acheddadi** [comment]
I installed it via nugget, by using the command `dotnet add package Raylib-cs --version 3.7.0.1`

Although I suspect that the project may be referring to my local shared library which I also have on my machine. I'm not quite sure how to force dotnet to use the supplied Niger package rather than a shared library.

**Comment by ChrisDill** [comment]
@acheddadi `DrawTextRec` is available in raylib 3.7 but removed in 4.0. What version is the shared library on your machine?

**Comment by acheddadi** [comment]
> @acheddadi `DrawTextRec` is available in raylib 3.7 but removed in 4.0. What version is the shared library on your machine?

Ah, that would explain it. The shared library I have on my machine is 4.0. Is there a way for me to specify that dotnet should only use the supplied DLL and not the shared library?

**Comment by 9ParsonsB** [comment]
You can try setting `LD_LIBRARY_PATH` or `LD_PRELOAD` environment variables, but this is a known issue with dotnet on Linux: https://github.com/dotnet/runtime/issues/34711
