### ISSUE TITLE
how to change opengl profile / graphics api in C# version? [question]

### ISSUE THREAD

**Issue by riffshark** [ChrisDill/Raylib-cs#105]
I could compile the c/c++/notepad++ version with
```
echo Set desired OpenGL API version: 1.1, 2.1, 3.3
SET GRAPHIC_API=GRAPHICS_API_OPENGL_21 // line 74
```
in notepads compile script *::raylib_source_compile* [link](https://github.com/raysan5/raylib/blob/master/projects/Notepad%2B%2B/npes_saved_mingw.txt)
but could not find a way how to change opengl profile / graphics api in C# version (my machine does not support preconfigured version)

Is it possible to do just with nuget package without cloning this repo?

**Comment by 9ParsonsB** [comment]
Hi @riffshark,

To do this, you need to compile `raylib` yourself as the version provided via NuGet is from `raylib`s GitHub Releases. Once you have compiled your own version, all you need to do is drop the library into the build folder of the application - there should be no need to clone this repo.

We currently have no plans to provide a custom version of `raylib` with `raylib-cs`

Let us know if you have any more question or issues 😄

**Comment by riffshark** [comment]
ok, I have next issue: I'm getting "System.BadImageFormatException" in Raylib-cs.dll on ```InitWindow()``` 
- I recompiled ```raylib.dll``` and ```/include/raylib.h``` with OpenGL2.1 (also tested in C that it works)
- I had to replace ```raylib.dll``` in ```C:\Users\USERNAME\.nuget\packages\raylib-cs\4.0.0.1\runtimes\win-x64\native``` beacause on each run the dll was copied and replaced
- on run this error occurs
how to fix this?

**Comment by 9ParsonsB** [comment]
The default build output folder is `bin/[Configuration]/[Framework]` Configuration is usually `Debug`, Framework is sometimes omitted.  The `win-x64/native` folder is used for runtime/OS specific libraries in their "native" format; our NuGet package copies the libraries there on build.

`BadImageFormatException` Can mean a lot of things, most likely that the file you are trying to inter-op with is not valid (i.e. it is corrupt or in the wrong format/file type)
