### ISSUE TITLE
Unable to load DLL 'raylib'

### ISSUE THREAD

**Issue by Nyxie98** [ChrisDill/Raylib-cs#111]
Trying to install this in Windows under the Manual Installation. Not sure if I'm missing something, or I've done something wrong, but I just keep getting this error when I try to run the demo

![image](https://user-images.githubusercontent.com/70954504/172232029-eb95e3ee-7edf-43f1-98d8-3e8496e03216.png)

**Comment by JupiterRider** [comment]
If you use the github repo, you have to put the raylib.dll into your root folder (where the csproj is). You can download it here:
[https://github.com/raysan5/raylib/releases/tag/4.0.0](https://github.com/raysan5/raylib/releases/tag/4.0.0)
It's the raylib-4.0.0_win64_msvc16.zip .

The repo doesn't contain the compiled shared library.

If you want to use Raylib-cs for your own game, I recommend you to use the nuget package:
[https://www.nuget.org/packages/Raylib-cs/](https://www.nuget.org/packages/Raylib-cs/)

The nuget package contains all libraries for windows, mac os and linux.
