### ISSUE TITLE
Would it be possible to create c# bindings for rres resource packer system?

### ISSUE THREAD

**Issue by SoloByte** [ChrisDill/Raylib-cs#113]
### Issue description
Dealing with exported resources in raylib with c# is complicated right now. 

The default way is to copy the resource folder to the output directory but when distributing your game/app all resources are visible to the customer. (among many other problems with that way)

The problem is that loading resources from anywhere else than the disk is very complicated or not possible. (to my knowledge with raylib c# bindings) So my only solution would be to compress/encrypt the resources when building and then uncompress/decrypt them when the game/app is started but then the resources are visible again to the user while the game/app is running.

Raysan already implemented a solution for raylib called [rres](https://github.com/raysan5/rres) but it is only available for c right now. The [resource packer](https://raylibtech.itch.io/rrespacker) can already be used to pack all the resources into a rres file but there is no way to load that rres file and transform it into raylib types like image, font, wave, etc. right now.

It would be really nice if there would be separate bindings for rres so it can be used with c# and it would make raylib with c# much more robust. 

PS: At least it would be nice to know if you are interested in doing that at all. Because I don´t need it right now and if you would like to do it I am not going to look for another solution. 

I will also ask [NotNotTech with raylib-cslo](https://github.com/NotNotTech/Raylib-CsLo/issues/19) bindings.

Thanks!

**Comment by ChrisDill** [comment]
@SoloByte We are interested in making resource loading easier and the rres project looks good for this. Though we have no plans to work on it at the moment.

**Comment by SoloByte** [comment]
@ChrisDill Thanks for the quick response!
I understand, no problem. I figured out a simple solution for packing resources and loading them at runtime. Once done I will post it here for future reference.

**Comment by SoloByte** [comment]
This is my simple solution for packing resources into 1 file to make the distribution of the build easier. 

I always set this in my project file:
`<RunWorkingDirectory>$(MSBuildThisFileDirectory)</RunWorkingDirectory>`
to make the paths relative to the project.

You need a single folder containing all the resources you want to pack. I mostly just have a resources folder with a structure like that in my project:

resources
-gfx
--exampe-texture.png
-audio
--sfx
---example-sound.wav
--music
---example-music.ogg
-fonts
--example-font.ttf
-shaders
--example-shader.fs

### To pack your resources you just have to call:
```
string sourcePath = "resources"; //because it is relative to the project that is enough
string outputPath = ""; //empty path puts it in the root of your project and the file is always called resources.txt
ResourceManager.Generate(sourcePath, outputPath);
```
And when you run the game in visual studio the file is created. 

**When you build the game and you want to launch it from the .exe file make sure to comment out the** `ResourceManager.Generate(sourcePath, outputPath)` **Function Call!**

Additionally you can right-click on the newly created resources.txt in visual studio, go to properties, and set "Copy To Output Directory" to "Always Copy" so the file is copied to the output directory when you build the game.

You could make a separate console app with the source code and use the .exe file in a pre-build event in visual studio to automate the process of packing the resources.


### Loading Resources
You need to create an instance of the ResourceManager Class and give it the path to the resources.txt file.
After that just call any of the Load Functions in the resource manager instance to load resources (Image, Texture, Font, Sound, Music, Shader, Json String).
```
var resourceManager = new ResourceManager(""); //because file is in the root of the project "" is enough
var texture = resourceManager.LoadTexture("example-texture");
var sound = resourceManager.LoadSound("example-sound");
var music = resourceManager.LoadMusic("example-music");
var font = resourceManager.LoadFont("example-font", 100);
var shader = resourceManager.LoadFragmentShader("example-shader");
```

### Source Code
```
public struct ResourceInfo
{
    public string extension;
    public byte[] data;

    public ResourceInfo(string extension, byte[] data) { this.extension = extension; this.data = data; }
}

public class ResourceManager
{
    private readonly Dictionary<string, ResourceInfo> resources;


    public ResourceManager(string path)
    {
        resources = LoadResources(path);
    }
    public static void Generate(string sourcePath, string outputPath)
    {
        string filename = "resources.txt";
        string[] files = Directory.GetFiles(sourcePath, "", SearchOption.AllDirectories);
        List<string> lines = new List<string>();
        foreach (var file in files)
        {
            lines.Add(Path.GetFileName(file));
            var d = File.ReadAllBytes(file);
            lines.Add(Convert.ToBase64String(Compress(d)));
        }
        File.WriteAllLines(outputPath + filename, lines);
     }


    public Texture2D LoadTexture(string name)
    {
        return Raylib.LoadTextureFromImage(LoadImage(name));
    }
    public Image LoadImage(string name)
    {
        unsafe
        {
            var data = resources[name].data;
            var extension = resources[name].extension;
        
            fixed (byte* ptr = data)
            {
                fixed (byte* p = Encoding.ASCII.GetBytes(extension))
                {
                    sbyte* sp = (sbyte*)p;
                    return Raylib.LoadImageFromMemory(sp, ptr, data.Length);
                }
            }
        }
    }
    public Font LoadFont(string name, int fontSize = 100)
    {
        unsafe
        {
            var data = resources[name].data;
            var extension = resources[name].extension;
            fixed (byte* ptr = data)
            {
                fixed (byte* p = Encoding.ASCII.GetBytes(extension))
                {
                    sbyte* sp = (sbyte*)p;
                    return Raylib.LoadFontFromMemory(sp, ptr, data.Length, fontSize, (int*)0, 300);
                }
            }
        }
    }
    public Wave LoadWave(string name)
    {
        unsafe
        {
            var data = resources[name].data;
            var extension = resources[name].extension;
            fixed (byte* ptr = data)
            {
                fixed (byte* p = Encoding.ASCII.GetBytes(extension))
                {
                    sbyte* sp = (sbyte*)p;
                    return Raylib.LoadWaveFromMemory(sp, ptr, data.Length);
                }
            }
        }
    }
    public Sound LoadSound(string name)
    {
        return Raylib.LoadSoundFromWave(LoadWave(name));
    }
    public Music LoadMusic(string name)
    {
        unsafe
        {
            var data = resources[name].data;
            var extension = resources[name].extension;
            fixed (byte* ptr = data)
            {
                fixed (byte* p = Encoding.ASCII.GetBytes(extension))
                {
                    sbyte* sp = (sbyte*)p;
                    return Raylib.LoadMusicStreamFromMemory(sp, ptr, data.Length);
                }
            }
        }
    } 
    public Shader LoadFragmentShader(string name)
    {
        string file = Encoding.Default.GetString(resources[name].data);
        return Raylib.LoadShaderFromMemory(null, file);
    }
    public string LoadJsonData(string name)
    {
        return Encoding.Default.GetString(resources[name].data);
    }




    private static byte[] Compress(byte[] data)
    {
        MemoryStream output = new MemoryStream();
        using (DeflateStream dstream = new DeflateStream(output, CompressionLevel.Optimal))
        {
            dstream.Write(data, 0, data.Length);
        }
        return output.ToArray();
     }
    private static byte[] Decompress(byte[] data)
    {
         MemoryStream input = new MemoryStream(data);
         MemoryStream output = new MemoryStream();
         using (DeflateStream dstream = new DeflateStream(input, CompressionMode.Decompress))
        {
            dstream.CopyTo(output);
        }
        return output.ToArray();
    }
    private Dictionary<string, ResourceInfo> LoadResources(string path)
    {
        Dictionary<string, ResourceInfo> result = new();
        var lines = File.ReadAllLines(path + "resources.txt");
        for (int i = 0; i < lines.Length; i += 2)
        {
            string filenName = lines[i];
            string name = Path.GetFileNameWithoutExtension(filenName);
            string extension = Path.GetExtension(filenName);
            string dataText = lines[i + 1];
            var data = Convert.FromBase64String(dataText);
            result.Add(name, new(extension, Decompress(data)));
        }
        return result;
    }
}

```

**Comment by GoldenQubicle** [comment]
Thanks @SoloByte your example helped me figuring out how to read a MagickImage directly from memory and display it as a RayLib image (instead write and then read from disk)
