### ISSUE TITLE
Raylib.LoadShader(sbyte* vsFileName, sbyte* fsFileName);

### ISSUE THREAD

**Issue by eliasstepanik** [ChrisDill/Raylib-cs#114]
### Issue description

*Hello,
i wanted to use the Raylib.LoadShader(sbyte* vsFileName, sbyte* fsFileName) fuction but I don´t know how to pass the sbyste*

**Comment by ChrisDill** [comment]
You can use the `Raylib.LoadShader` wrapper function to pass in strings instead which handles that for you. What data are you trying to pass into it?

**Comment by eliasstepanik** [comment]
I´m trying to pass the path to raymarching.fs

**Comment by eliasstepanik** [comment]
Ok I found it. Thanks
