### ISSUE TITLE
GetScreenWidth and GetScreenHeight returning wrong values

### ISSUE THREAD

**Issue by vinnyhorgan** [ChrisDill/Raylib-cs#123]
Hi, i've noticed that, after i resize my window with SetWindowSize(), the values that these two functions return is wrong, and references the previous window size.

**Comment by JupiterRider** [comment]
Hey,
Once you've changed the windows size, you'll have to wait until the next game loop (Raylib.WindowShouldClose). 
Then the values are updated and correct.

I think this is not Raylib-cs related, because these methods are direct interop with the native library.
