### ISSUE TITLE
Raylib 4.2 Support

### ISSUE THREAD

**Issue by Shpendicus** [ChrisDill/Raylib-cs#128]
https://github.com/NotNotTech/Raylib-CsLo/issues/21#issue-1362467000

its only regarding if u plan to work on the major release of 4.2 :)

**Comment by 9ParsonsB** [comment]
Yes, we are working on 4.2, there is a branch with all the changes. 
I believe the release will be very soon. 

We wanted to release a service update to 4.0.0 first (4.0.0.2), which is now done.

**Comment by Shpendicus** [comment]
Very nice to hear, thanks!

BTW: right now, in the Version 4.0.2; Is it that that current version, you are already able to reference REVIEWED/UPDATED functions from raylib automatically?? like if ur lib is already referencing raylib 4.2, will the end-user of your 4.0.2 be able to use ACTUALLY a function from the 4.2 from raylib, or does ur 4.0.2 reference sill only the older function from raylib 4.0.2

Short example:
YourRaylib(4.0.2) --------> references: (Raylib 4.2)
User -------> calls: "Raylib_cs.DrawPixel(blaaablaaa)" -------->internally your lib calls into which version of raylib?

I ask this, because it woule be cool without any touch of code that your project will ALWAYS reference the up to date raylib library just by recompiling the entire project, am I right?

**Comment by graphnode** [comment]
> I ask this, because it woule be cool without any touch of code that your project will ALWAYS reference the up to date raylib library just by recompiling the entire project, am I right?

You mean using the [raylib parser](https://github.com/raysan5/raylib/tree/master/parser)? I've looked at it and it will need some hardcoded fixes to fit C# code style. Example: Color static fields instead of using preprocessor directives.

**Comment by Shpendicus** [comment]
@graphnode I am disappointed at you! SHAME SHAME!

...

Joke :D. 

Dont worry, was just a question, but as the saying goes, "It would have been to good to be true" xD

Wish you good success tho :)

**Comment by Shpendicus** [comment]
@graphnode Mate sry if i am annoying here, I am just burning to know if you are currently updating to 4.2 raylib^^

Would be cool to know, cheers

**Comment by 9ParsonsB** [comment]
Please see the 4.2 branch if you would like to try out the new release.
