### ISSUE TITLE
Nuget release

### ISSUE THREAD

**Issue by ChrisDill** [ChrisDill/Raylib-cs#13]
- Nuget package with no extra setup needed.
- Reduce use of unsafe with features like Span.
- Bundle mac and linux builds of raylib(.so .dylib ).
- Add bindings to Rlgl.
- Physac binding needs to be fixed.

**Comment by ChrisDill** [comment]
Update on this issue.
Bindings are on nuget currently unlisted. 
I have tested them and they work but still subject to change.

**Comment by rfaa00** [comment]
Hey, I'm currently trying the 1.4.0 version of the nuget but I can't seem to use anything from it? Do I have to do something extra to get access to the methods?

**Comment by ChrisDill** [comment]
So it says its installed but says they do not exist when you try to use them?

I have a similar issue with netcore that needs to be fixed. For some reason it does not add the bindings to the project.

**Comment by rfaa00** [comment]
Basically yes, the nuget installs fine but I cannot find any references to Raylib when coding. I'm using net core 2.1 with vscode, the 1.0.2 version of the nuget seems to work, although I have to copy the dll to the project to get it to run.

**Comment by Shadowblitz16** [comment]
is this not going to be done?
it would be really nice if everything was in a neat little package.

**Comment by ChrisDill** [comment]
@Shadowblitz16 This issue was my first attempt. It is something I am looking into fixing but there are some issues figuring out how to handle the native libraries. See issue #43 for details.
