### ISSUE TITLE
[Monitors/Linux] When run from vs code or command line game does not start on the primary display

### ISSUE THREAD

**Issue by allora** [ChrisDill/Raylib-cs#131]
Before submitting a new issue, please verify and check:

 - [x] The issue is specific to Raylib-cs and not raylib
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of Raylib-cs

### Issue description

When the hello world project starts from VSCode in linux with multiple displays via F5, or from the command line, from a terminal or VSCode on the primary display, the game starts on a different monitor entirely (not the primary, or the focused display). Doing this in C, instead of C# results in expected behavior, where the game shows up on the display  VSCode/terminal is on.

### Steps
- Use archlinux and have 2 or more monitors (I have 3 of asymmetric size)
- Grab the hello world project
- Open VSCode onto the primary display
- Launch the game using F5
- Game window appears on some other display

### Environment
- Hardware: Ryzen 5950X, Radeon 6700XT, 64GB Ram
- Distro: Arch Linux
- Window Manager: BSPWM
- 3 Displays of varying resolutions (640x480, 1920x1080, 2560x1440)

### Code example
Use the hello world example.

**Comment by ChrisDill** [comment]
@allora What version of Raylib-cs are you using and which version of raylib did you test to compare?

**Comment by XReaper95** [comment]
I can confirm this was fixed here https://github.com/raysan5/raylib/pull/2731, as I always had the same problem in Manjaro. Building the `master` branch from source gives the correct window position on my main monitor. I guess it has not been released yet.

**Comment by allora** [comment]
Sorry for the delayed response, life gets busy sometimes :D

Trying this again, with Raylib-cs through Nuget (version 4.5.0) and in Rider, the created window still appears on a secondary monitor, despite this being marked fixed upstream.

**Comment by ChrisDill** [comment]
Thanks for the update on this. If it works upstream then that fix can be included in Raylib-cs once part of an official release.
