### ISSUE TITLE
[Core] Gamepad axis is not correct.

### ISSUE THREAD

**Issue by Shadowblitz16** [ChrisDill/Raylib-cs#132]
Before submitting a new issue, please verify and check:

 - [x] The issue is specific to Raylib-cs and not raylib
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of Raylib-cs

### Issue description
GetGamepadAxisMovement() does not returns correct values.
It seem trying to print a object or move it around only lets it move 8 ways not 360...

### Environment

OS: KDE neon 5.25
Processors: 16 x AMD Ryzen 7 5700G with Radeon Graphics
Graphics Procceser: AMD RENOIR

### Issue screenshot
Na

### Code example

```cs
    protected override void OnUpdate()
    {
        base.OnUpdate();
        //Physics.VX = (Input["Right"].GetValue(0.25f) - Input["Left"].GetValue(0.25f)) * Speed;
        //Physics.VY = (Input["Down" ].GetValue(0.25f) - Input["Up"  ].GetValue(0.25f)) * Speed;
        //Console.WriteLine("VX:"+Physics.VX);

        Physics.VX = Raylib_cs.Raylib.GetGamepadAxisMovement(0, Raylib_cs.GamepadAxis.GAMEPAD_AXIS_LEFT_X);
        Physics.VY = Raylib_cs.Raylib.GetGamepadAxisMovement(0, Raylib_cs.GamepadAxis.GAMEPAD_AXIS_LEFT_Y);
    }
```

```cs
    protected override void OnUpdate()
    {
        base.OnUpdate();

        Console.WriteLine
        (
            "AXIS X:"+Raylib_cs.Raylib.GetGamepadAxisMovement(0, Raylib_cs.GamepadAxis.GAMEPAD_AXIS_LEFT_X) + ", "+
            "AXIS Y:"+Raylib_cs.Raylib.GetGamepadAxisMovement(0, Raylib_cs.GamepadAxis.GAMEPAD_AXIS_LEFT_Y)
        );
    }
```

**Comment by JupiterRider** [comment]
Hey @Shadowblitz16 

You can calculate the angle in degrees like this:

```csharp
Vector2 left = new();
left.X = Raylib.GetGamepadAxisMovement(0, GamepadAxis.GAMEPAD_AXIS_LEFT_X);
left.Y = Raylib.GetGamepadAxisMovement(0, GamepadAxis.GAMEPAD_AXIS_LEFT_Y);

float Vector2ToAngleDegrees(Vector2 v)
{
    float angle = MathF.Atan2(v.X, v.Y) * 180 / MathF.PI;

    if (angle < 0)
    {
        angle += 360;
    }

    return angle;
} 
```

Here is a great explanation from a competing game engine about vector math:
https://docs.godotengine.org/en/stable/tutorials/math/vector_math.html

**Comment by Shadowblitz16** [comment]
@JupiterRider that doesn't make sense gamepad joy's should return a vector between -1 and 1
if you take the value of GAMEPAD_AXIS_LEFT_X and GAMEPAD_AXIS_LEFT_Y you can modify velocity or position's x and y directly.

This is how engines like gamemaker and godot dot it.

I also tested this with c raylib can't the C# version doesn't match

**Comment by JupiterRider** [comment]
@Shadowblitz16 
First of  all, this behavior is not Raylib-cs specific.

Can you give us a more concrete example of the values you get and the values you except?

**Comment by Shadowblitz16** [comment]
I messed up the project because I'm a bad programmer but I expect a unit circle depending or the direction and length of how hard I press the joystick.

for example it should be...

```cs
joyAxisX =  MathF.Cos(joyAxisDir) * joyAxisLen;
joyAxisY = -MathF.Sin(joyAxisDir ) * joyAxisLen;
``` where joyAxisLen is no greater then 1.

**Comment by Shadowblitz16** [comment]
Also your right this is a c raylib issue.
