### ISSUE TITLE
[General] Add Rl- prefix to types to avoid naming conflicts

### ISSUE THREAD

**Issue by Fallbork** [ChrisDill/Raylib-cs#135]
One common practice with Raylib-cs is to write `global using static` declarations in order to approximate the ease-of-usage of the original raylib. Generic names like the ones we currently have for the type structs clash with other libraries such as [Box2D .NET Standard](https://github.com/codingben/box2d-netstandard) (primarily the Color and Transform structs, from what I've noticed). This problem could be fixed for ALL libraries with the addition of a simple `Rl-` prefix behind each type that prevents ambiguity, and it's a change that shouldn't really take more than a couple minutes to implement. Codebases that already depend on this repo can also run a quick "Replace All" operation to change existing declarations.

**Comment by ChrisDill** [comment]
Changing the naming across all types would be a big breaking change for not enough benefit. I have not seen `global using static` used much myself. I suggest static usings be done per file if naming conflicts are likely to occur.

**Comment by Fallbork** [comment]
I see... well, if that's the case then i'll be closing this issue then! Thank you for the attention :D
