### ISSUE TITLE
Old OpenGL compatibility

### ISSUE THREAD

**Issue by Me2L** [ChrisDill/Raylib-cs#136]
How new does my OpenGL have to be to use raylib-cs 3.0 in Visual Studio 2017?

**Comment by JupiterRider** [comment]
Raylib-cs uses OpenGL 3.3, which is also the default of raylib: [https://github.com/raysan5/raylib/blob/master/src/Makefile#L230](https://github.com/raysan5/raylib/blob/master/src/Makefile#L230)

But I think your biggest Issue is VS 2017, which doesn't support .NET 5 or higher. Raylib-cs needs at least .NET 5.
