### ISSUE TITLE
[nuget] Publish a nuget package without a hyphen

### ISSUE THREAD

**Issue by stanoddly** [ChrisDill/Raylib-cs#141]
Currently it's not possible to use Raylib-cs for .NET 7 WASM build due to the hyphen in the name. I reported the issue to dotnet/runtime and it has been already fixed and merged to main, see https://github.com/dotnet/runtime/issues/78992

However it might take a while before we see that in `7.0.x` as I requested in ⬆️. Right now the target is 7.0.3 of the back-port PR:
https://github.com/dotnet/runtime/pull/79175

Even if they manage to successfully back-port the fix to `7.0.3`, based on [6.0.3](https://versionsof.net/core/6.0/) it would take 3+ months before we see that.

So yes, admittedly publishing a nuget package without a hyphen would basically be a workaround for broken functionality in dotnet. I can try to prepare the `.csproj` and adjust a GitHub workflow if there is enough interest.

**Comment by ChrisDill** [comment]
Ideally Raylib-cs should be a single package for all platforms. I don't mind publishing a temporary version to workaround this issue though the name/description should be clear to prevent confusion for new users.

**Comment by disketteman** [comment]
Completely agree, this is truly just a workaround which would allow to use the library as a proper nuget dependency for Web. In my prototype I had to copy Raylib-cs as a workaround:
https://github.com/disketteman/DotnetRaylibWasm/tree/main/Raylib_cs
(Plus I removed some obsolete raylib functions, but IIRC that's it)

BTW I can obviously publish a package with a different name on my own manually, however I'm bit afraid that it wouldn't look very... legitimate?

Anyway what next steps do you suggest?

**Comment by ChrisDill** [comment]
@disketteman I think we should first look at adding the wasm support changes needed to the library/examples. From there I can test some ideas and get a better idea of what should be done on the packaging side.

**Comment by disketteman** [comment]
@ChrisDill what if _somebody_ did that for us already? 😄 
https://github.com/disketteman/DotnetRaylibWasm

**Comment by ChrisDill** [comment]
By that I meant merging those changes upstream. :smile: In the meantime, I will look at setting up the project *somebody* made locally so I can test some ideas.

**Comment by disketteman** [comment]
So far I found these issues:
- https://github.com/disketteman/DotnetRaylibWasm/issues/11
  - easy
- https://github.com/disketteman/DotnetRaylibWasm/issues/5
  - this ticket is about that
- https://github.com/disketteman/DotnetRaylibWasm/issues/4
  - no idea, but I can live without them

I can report them separately and also report a WebAssembly build, however it's more complicated because raylib must be compiled with the very same version of emscripten as the project. It's because emscripten doesn't follow semver (mentioned [here](https://github.com/emscripten-core/emscripten/issues/10683#issuecomment-597940697)).

**Comment by ChrisDill** [comment]
Thanks! No need to report separately. We can track those issues in your project.
Though worth mentioning #118 could maybe help with ensuring the same emscripten version is used.

**Comment by ChrisDill** [comment]
@stanoddly Sorry for leaving this open for so long. Have not kept up to date on wasm progress so I am not sure on the status of this. Are the 3 issues still blocking this?

Looks like someone got it to work with the nuget package for https://github.com/stanoddly/DotnetRaylibWasm/issues/5 though that needs to be tested with the latest package to be sure. Also worth mentioning some progress has been made with custom builds though still experimental at the moment.

Also I noticed the zlib license isn't in your project. Can you add this for the Raylib-cs library/examples as it is not the same as the MIT license. Thanks!

**Comment by ChrisDill** [comment]
Closing since the hyphen in the name is no longer an issue.
