### ISSUE TITLE
Please add support for all c raylib targets

### ISSUE THREAD

**Issue by SB16Tech** [chrisdill/Raylib-cs#144]
Before submitting a new issue, please verify and check:

 - [x] The issue is specific to Raylib-cs and not raylib
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of Raylib-cs

### Issue description
Can we get more platform support for raylib-cs?
It might be one of the things that make raylib-cs stand out from monogame, opentk and silk.net

Maybe even android?

### Environment
Debian 11 

### Issue screenshot
![image](https://user-images.githubusercontent.com/124482250/217433607-e4d807ef-ae48-436f-aa9b-377b51a419f0.png)

**Comment by JupiterRider** [comment]
**RaspberryPi** is possible, but you have to build the shared library (libraylib.so) yourself. You can find instructions here:
https://github.com/raysan5/raylib

For **FreeBSD** you'll have to wait, because the official support of dotnet is in the making:
https://github.com/dotnet/runtime/issues/14537

**HTML5** is technically possible via dotnet 7 and native aot. Here is a repo of a guy who made it work:
https://github.com/disketteman/DotnetRaylibWasm

For **Android** there's an open issue: https://github.com/ChrisDill/Raylib-cs/issues/87

**Comment by SB16Tech** [comment]
> **RaspberryPi** is possible, but you have to build the shared library (libraylib.so) yourself. You can find instructions here: https://github.com/raysan5/raylib

It would be nice if this wasn't needed..
> 
> For **FreeBSD** you'll have to wait, because the official support of dotnet is in the making: [dotnet/runtime#14537](https://github.com/dotnet/runtime/issues/14537)
ok cool.

> 
> **HTML5** is technically possible via dotnet 7 and native aot. Here is a repo of a guy who made it work: https://github.com/disketteman/DotnetRaylibWasm
This should be merged into this repo preferably packing in the js stuff into the nuget package

> 
> For **Android** there's an open issue: #87
This should also be merged into this repo

anyways what about consoles?

**Comment by anggape** [comment]
sorry for slow response, i think i accidentally deleted the previous implementation while ago, but i reimplement it again here https://github.com/anggape/Raylib-cs/tree/android

**Comment by anggape** [comment]
added github actions for building from sources instead of copying native library from raylib releases https://github.com/anggape/Raylib-cs/tree/native-runtimes

i also added android build https://github.com/anggape/Raylib-cs/tree/android

tag @ChrisDill

**Comment by chrisdill** [comment]
Ended up removing the android example since the custom setup was not fully setup/worth maintaining. Still open to more platform support but it should use the existing project structure to keep it simple.

**Comment by chrisdill** [comment]
Though moving forward I am not planning to add more platforms myself except maybe wasm but will consider any PR's for them.
