### ISSUE TITLE
[Request] Add dylib for arm64 to build on M1 Mac

### ISSUE THREAD

**Issue by leftbones** [ChrisDill/Raylib-cs#145]
This long-standing issue was recently solved in Raylib-CsLo, see https://github.com/NotNotTech/Raylib-CsLo/issues/28

I found previous issues regarding this that were closed without any solution, please consider using the above example to put an end to it once and for all.

Thank you!

**Comment by JupiterRider** [comment]
Hey @leftbones,
it is fixed with a solution, but a maintainer hast to update the nuget package.

**Comment by JupiterRider** [comment]
@9ParsonsB @ChrisDill Could someone of you may do this :) ?

**Comment by ChrisDill** [comment]
@leftbones Like @JupiterRider said, the fix is there but not on nuget yet. Planning to make a point release with a few fixes which will include this change.

**Comment by ChrisDill** [comment]
The 4.2.0.2 release is now out. Let me know if this fixes the issue.

**Comment by ChrisDill** [comment]
Closing as the issue should now be resolved.
