### ISSUE TITLE
[raymath] Raymath.Vector2Clamp is incorrect and possiably other functions

### ISSUE THREAD

**Issue by Shadowblitz16** [ChrisDill/Raylib-cs#146]
Before submitting a new issue, please verify and check:

 - [x] The issue is specific to Raylib-cs and not raylib
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of Raylib-cs

### Issue description

Raylib-cs's Raymath.Clamp does not include min and max parameters
 
### Environment

Debain 11

### Issue screenshot

![image](https://user-images.githubusercontent.com/2453707/220232168-32055b98-7e39-478c-a024-36ae4082499f.png)

**Comment by ChrisDill** [comment]
Fix added in #147 and will be in the next release.
