### ISSUE TITLE
invalid description of IsCursorOnScreen method

### ISSUE THREAD

**Issue by localwhale20** [ChrisDill/Raylib-cs#150]
### Issue description

IsCursorOnScreen must have 'Check if cursor is on the screen' in comment/description, but have 'Disables cursor (lock cursor)' instead

### Environment

Raylib-cs 4.2.0.2

### Issue screenshot

![image](https://user-images.githubusercontent.com/61111955/227563207-59357e24-739b-42f7-8a1b-798453ad6b4b.png)
![image](https://user-images.githubusercontent.com/61111955/227563289-95641d27-21bd-4731-881e-326e0190792d.png)

**Comment by JupiterRider** [comment]
@localwhale20 Thank you for reporting! 

@ChrisDill I made a pull request for that #151
