### ISSUE TITLE
CheckCollisionLines returns false negatives

### ISSUE THREAD

**Issue by BlueCloudDev** [ChrisDill/Raylib-cs#153]
Before submitting a new issue, please verify and check:

 - [x ] The issue is specific to Raylib-cs and not raylib
 - [ x] I checked there is no similar issue already reported
 - [ x] My code has no errors or misuse of Raylib-cs

### Issue description

What I'm seeing is that the collision detection algorithms, specifically Line-Line collision, only works sometimes. My current case is I have an enemy entity with 8 lines split evenly by radians around the entity as collision 'sensors' as part of my steering algorithm. I need to know if any of those lines intersect with another line (a wall) to avoid it. When running the collision detection system provided in this repo, if I place a circle at the collision point every frame, for every sensor, that circle will rapidly blink, indicating that it returns a false negative sometimes.

If I isolate the code with a completely separate simple example, the detection works as expected, the circle drawn at the interesection does not blink, and always detects the collision.

As a fix, I wrote my own line-line collision detection, which works, but I'd like to understand what's happening with the provided methods.

### Environment

Windows 11, Visual Studio Community latest version

### Issue screenshot
Units should not be able to path through objects on the map. Pink dots indicate collisions being detected with the invisible sensor lines.
Green/blue lines indicate steering, not related to this issue. Notice the dots will sometimes blink, and other times work as expected.

[Imgur link to issue demo](https://i.imgur.com/rlWEbwn.mp4)

### Code example

If you uncomment the Raylib.CheckCollisionLines line and comment the line below it, the above behavior is produced. If not, it works without issue using my own line-line collision detection.

```
  public (bool, double) GetDistClosestFeatureCollision(EnemyUnit eu, double radians)
  {
      var end = VectorOperations.VectorExtendRadiusAlongRadians(eu.Position, radians, eu.Radius*5);
      bool hasCollided = false;
      var closestCollisionDist = double.MaxValue;
      foreach (var feature in GameState.CurrentLevel.Features)
      {
          if (feature.FeaturePath.Count < 2)
          {
              continue;
          }
  
          Vector2 prevPoint = feature.FeaturePath[0];
          for (int i = 1; i <= feature.FeaturePath.Count; i++)
          {
              if (i == feature.FeaturePath.Count)
              {
                  i = 0;
              }
              var pathCollision = new Vector2();
  
              //var collide = Raylib.CheckCollisionLines(eu.Position, end, prevPoint, feature.FeaturePath[i], ref pathCollision);
              var collide = CollisionDetection.CheckCollisionLineLine(eu.Position, end, prevPoint, feature.FeaturePath[i], ref pathCollision);
              if (collide)
              {
                  hasCollided = true;
                  var dist = PlaneOperations.GetDistance(eu.Position, pathCollision);
                  if (dist < closestCollisionDist)
                  {
                      eu.Steering.DangerCollisionPoints.Add(pathCollision);
                      closestCollisionDist = (double)dist;
                  }
              }
              if (i == 0)
              {
                  break;
              }
              prevPoint = feature.FeaturePath[i];
          }
      }
      return (hasCollided, closestCollisionDist);
  }

```

**Comment by BlueCloudDev** [comment]
> Hey, this is what happens: https://github.com/raysan5/raylib/blob/master/src/rshapes.c#L1710

Yes, understood. What I want to know is why it's sometimes returning false negatives.

**Comment by n77y** [comment]
Hi @BlueCloudDev, could you try and reproduce this issue with this line-line collision code? I took it from raylib and modified it so its C# code. I have so far been unable to repro this issue using the Raylib-cs binding.
```C#
public static CBool CheckCollisionLines(Vector2 startPos1, Vector2 endPos1, Vector2 startPos2, Vector2 endPos2, ref Vector2 collisionPoint)
{
    bool collision = false;

    float div = (endPos2.Y - startPos2.Y) * (endPos1.X - startPos1.X) - (endPos2.X - startPos2.X) * (endPos1.Y - startPos1.Y);

    if (float.Abs(div) >= float.Epsilon)
    {
        collision = true;

        float xi = ((startPos2.X - endPos2.X) * (startPos1.X * endPos1.Y - startPos1.Y * endPos1.X) - (startPos1.X - endPos1.X) * (startPos2.X * endPos2.Y - startPos2.Y * endPos2.X)) / div;
        float yi = ((startPos2.Y - endPos2.Y) * (startPos1.X * endPos1.Y - startPos1.Y * endPos1.X) - (startPos1.Y - endPos1.Y) * (startPos2.X * endPos2.Y - startPos2.Y * endPos2.X)) / div;

        if (((float.Abs(startPos1.X - endPos1.X) > float.Epsilon) && (xi < float.Min(startPos1.X, endPos1.X) || (xi > float.Max(startPos1.X, endPos1.X)))) ||
            ((float.Abs(startPos2.X - endPos2.X) > float.Epsilon) && (xi < float.Min(startPos2.X, endPos2.X) || (xi > float.Max(startPos2.X, endPos2.X)))) ||
            ((float.Abs(startPos1.Y - endPos1.Y) > float.Epsilon) && (yi < float.Min(startPos1.Y, endPos1.Y) || (yi > float.Max(startPos1.Y, endPos1.Y)))) ||
            ((float.Abs(startPos2.Y - endPos2.Y) > float.Epsilon) && (yi < float.Min(startPos2.Y, endPos2.Y) || (yi > float.Max(startPos2.Y, endPos2.Y))))) collision = false;

        if (collision)
        {
            collisionPoint.X = xi;
            collisionPoint.Y = yi;
        }
    }

    return collision;
}

**Comment by ChrisDill** [comment]
@BlueCloudDev Any update on this. Are you able to reproduce the issue with the example @n77y provided?

**Comment by BlueCloudDev** [comment]
I put down the project for a while, but can try picking it up again. I'm not clear on the ask, though. I am using the Raylib.CheckCollisionLines binding to produce the issue already. If I code the line-line collision myself, the issue is not produced.

I also wasn't able to reproduce the issue in a vaccuum. It seemed to happen once I scaled up the number of detections I was doing per frame. I'd need to do more experimentation to further confirm and isolate.

**Comment by ChrisDill** [comment]
Can you share your own collision checking code. Is it similar to what @n77y provided? I suggest adding some code to keep track one of the units so you can log details about it and see if there are any strange values when it is near a object.

**Comment by BlueCloudDev** [comment]
`public bool CheckCollisionLineLine(Vector2 v1, Vector2 v2, Vector2 v3, Vector2 v4, ref Vector2 intersection)
        {

            // calculate the distance to intersection point
            //float uA = ((x4 - x3) * (y1 - y3) - (y4 - y3) * (x1 - x3)) / ((y4 - y3) * (x2 - x1) - (x4 - x3) * (y2 - y1));
            float uA = ((v4.X - v3.X) * (v1.Y - v3.Y) - (v4.Y - v3.Y) * (v1.X - v3.X)) / ((v4.Y - v3.Y) * (v2.X - v1.X) - (v4.X - v3.X) * (v2.Y - v1.Y));
            //float uB = ((x2 - x1) * (y1 - y3) - (y2 - y1) * (x1 - x3)) / ((y4 - y3) * (x2 - x1) - (x4 - x3) * (y2 - y1));
            float uB = ((v2.X - v1.X) * (v1.Y - v3.Y) - (v2.Y - v1.Y) * (v1.X - v3.X)) / ((v4.Y - v3.Y) * (v2.X - v1.X) - (v4.X - v3.X) * (v2.Y - v1.Y));

            // if uA and uB are between 0-1, lines are colliding
            if (uA >= 0 && uA <= 1 && uB >= 0 && uB <= 1)
            {

                // optionally, draw a circle where the lines meet
                intersection.X = v1.X + (uA * (v2.X - v1.X));
                intersection.Y = v1.Y + (uA * (v2.Y - v1.Y));

                return true;
            }
            return false;
        }`

Code is re-worked for C# vectors based on: https://www.jeffreythompson.org/collision-detection/line-line.php
