### ISSUE TITLE
Vector class with overloaded operations

### ISSUE THREAD

**Issue by JasimAlrawie** [ChrisDill/Raylib-cs#154]
plz add Vector3 and Vector2 :D

**Comment by 9ParsonsB** [comment]
Hi, thanks for opening an issue.

To which methods would you like to add Vector2 & Vector3 support?

Can you post an example of what you are having trouble with and/or how you would like it to ideally work?

**Comment by ChrisDill** [comment]
@JasimAlrawie Raylib-cs uses System.Numerics for Vector2 and Vector3 types. It used to use custom types but was changed to make it easier to use with other libraries.

**Comment by JasimAlrawie** [comment]
@ChrisDill yep i discovered this lately 😅
