### ISSUE TITLE
[Feature] shapes drawing with integer 

### ISSUE THREAD

**Issue by JasimAlrawie** [ChrisDill/Raylib-cs#155]
its better to draw with floating point 
integers will get chopy results sometimes :(

**Comment by 9ParsonsB** [comment]
Could you please post a code example or show what issue you are encountering?

**Comment by ChrisDill** [comment]
@JasimAlrawie The functions match raylib which uses integers for the default shape drawing functions such as DrawRectangle. However there are alternative shape drawing functions that take in Vector2 and Rectangle which use float.

**Comment by JasimAlrawie** [comment]
@ChrisDill i think its better to use floating point for all shapes by default to give the flexibility and smooth movement

**Comment by JupiterRider** [comment]
@JasimAlrawie The functions with integers are converted to float anyway: https://github.com/raysan5/raylib/blob/master/src/rshapes.c#L720

**Comment by n77y** [comment]
@JasimAlrawie, are you looking for somthing like this?
```c#
/// <summary>Draw a color-filled rectangle</summary>
public static void DrawRectangle(float posX, float posY,  float width, float height, Color color)
{
    DrawRectangleV(new Vector2(posX, posY), new Vector2(width, height), color);
}

**Comment by ChrisDill** [comment]
Closing as I don't plan on changing this in the library as it works the same as raylib does. I suggest writing utils like what @n77y shared that are specific to your needs instead.
