### ISSUE TITLE
[module] Unsure how to properly use ChangeDirectory()

### ISSUE THREAD

**Issue by differenceclouds** [ChrisDill/Raylib-cs#156]
So, I'm using Raylib-CS on macos, so that might be pertinent. Right now, for loading assets I am using a solution I picked up from using Monogame. It goes something like this:
Check "copy to output directory" on all assets (images etc). Then I use this function whenever I'm loading a file:
```
static string getFullPath(string relativePath)
{
	string baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
	return System.IO.Path.Combine(baseDirectory, relativePath);
}

Font ALAGARD = LoadFont(getFullPath("Assets/fonts/alagard.png"));
Image cursorImage = LoadImage(getFullPath("Assets/cursor.png"));
```
This works for me, but I've been made aware that another solution would be to call `ChangeDirectory(GetApplicationDirectory());`

The issue is, I don't know how to use this function properly with C#. I get the following errors:
![Screen Shot 2023-06-08 at 12 03 34 PM](https://github.com/ChrisDill/Raylib-cs/assets/8020773/afe38d72-3bcd-40d1-b1ca-0ed84b329f41)
![Screen Shot 2023-06-08 at 12 03 39 PM](https://github.com/ChrisDill/Raylib-cs/assets/8020773/0ea3a12c-eeca-4d85-8895-7707ed8079f8)

Again, what I was already doing works, but I'm curious how to use these functions properly. It doesn't seem like using "unsafe" should be required. I feel that I am missing something obvious here, any help would be appreciated!

**Comment by 9ParsonsB** [comment]
Have a look at `Utf8StringUtils` it allows you to convert pointers to strings and back.

As for the current directory, try and prefer the built-in C# methods, e.g. prefer System.Numerics over RayMath,  `AppDomain.CurrentDomain.BaseDirectory` or `Assembly.GetExecutingAssembly().Location` over `raylib.GetApplicationDirectory`, etc.

**Comment by JupiterRider** [comment]
I think we should make these methods internal and provide a safe method for every one to not confuse the users.

**Comment by differenceclouds** [comment]
Maybe it's worth taking a look at all the methods that take pointers. I've gotten the image manipulation functions to work with the "ref" keyword but this wasn't obvious.

**Comment by JupiterRider** [comment]
@differenceclouds 
Oh, the `ref` keyword is common in C#:
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref

When you use `void ImageRotateCW(ref Image image)` for example, the with and height of the image change and in order to update the fields, you have to provide a reference. 

That's because Image is a struct and not a class.
