### ISSUE TITLE
[Bug] Transform.rotation use `Vector4` instead of `Quaternion`

### ISSUE THREAD

**Issue by MrScautHD** [ChrisDill/Raylib-cs#157]
Before submitting a new issue, please verify and check:

 - [x] The issue is specific to Raylib-cs and not raylib
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of Raylib-cs

### Issue description

Hello, I worked on my Camera rotation and saw the `Transform.rotation` use `Vector4` instead of `Quaternion`.
It should get changed to it becuase Methods like `Raymath.QuaternionToEuler` use `Quaternion`.

I hope i could help! :)

### Environment
- Raylib-cs [4.5.0.1]

### Issue screenshot
![grafik](https://github.com/ChrisDill/Raylib-cs/assets/65916181/477d9306-277f-4b97-9a03-99d015de314f)
![grafik](https://github.com/ChrisDill/Raylib-cs/assets/65916181/fd47401c-3657-424b-a830-dac86945d590)

**Comment by ChrisDill** [comment]
#158 merged. Thanks for the fix!
