### ISSUE TITLE
code usage

### ISSUE THREAD

**Issue by mfkl** [ChrisDill/Raylib-cs#159]
Looks like you used some code from libvlcsharp. A mention/credits would be nice.

**Comment by ChrisDill** [comment]
@mfkl Thanks for letting me know. Yes, I did adapt the logging from a dotnet github issue. Sorry about that. I will add a comment at the top of that file saying who wrote it/where it is from, is that okay?

**Comment by mfkl** [comment]
Appreciate it, thanks!
