### ISSUE TITLE
[Feature] Replace Raylib.Rectangle with System.Rectangle

### ISSUE THREAD

**Issue by MrScautHD** [ChrisDill/Raylib-cs#161]
Before submitting a new issue, please verify and check:

 - [x] The issue is specific to Raylib-cs and not raylib
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of Raylib-cs

### Issue description

Hello!
What you think about by removing the Rectangle struct, because C# has already a own class for it.

Let me know what you think about it, i can do the PR for it :)

**Comment by MrScautHD** [comment]
PS: It has exact the same functions

**Comment by ChrisDill** [comment]
Using a existing class sounds good however System.Drawing is not cross platform.
https://learn.microsoft.com/en-us/dotnet/api/system.drawing?view=net-7.0

**Comment by MrScautHD** [comment]
Read this text:

```cs
Some types in the System.Drawing namespace rely on [GDI+](https://learn.microsoft.com/en-us/windows/win32/gdiplus/-gdiplus-gdi-start), which is not supported in Windows services and ASP.NET Core and ASP.NET apps. These types are in the [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/) NuGet package and include [System.Drawing.Bitmap](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.bitmap?view=net-7.0) and [System.Drawing.Font](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.font?view=net-7.0). However, primitive types in the namespace, such as [System.Drawing.Color](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.color?view=net-7.0), [System.Drawing.Size](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.size?view=net-7.0), [System.Drawing.Point](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.point?view=net-7.0), and [System.Drawing.Rectangle](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.rectangle?view=net-7.0), can be used in any application.
```

**Comment by MrScautHD** [comment]
primitive types in the namespace, such as [System.Drawing.Color](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.color?view=net-7.0), [System.Drawing.Size](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.size?view=net-7.0), [System.Drawing.Point](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.point?view=net-7.0), and [System.Drawing.Rectangle](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.rectangle?view=net-7.0), can be used in any application.

**Comment by ChrisDill** [comment]
The types could be used but it means users need to be aware of what features of System.Drawing they can safely use. I would rather try to have features of the library work the same across platforms as best I can.

**Comment by MrScautHD** [comment]
well ok! Btw do you have dc?

**Comment by MrScautHD** [comment]
I think even Vector2 should get replaced with Size... but what ever it is your lib :/

**Comment by MrScautHD** [comment]
I saw, you need to impliment a special LIB for using the other stuff.

If you give me the ok, i can do it! :)

**Comment by ChrisDill** [comment]
Not sure what you are asking. By special lib do you mean System.Numerics?

**Comment by MrLiquid4k** [comment]
I like it!

**Comment by MrScautHD** [comment]
> The types could be used but it means users need to be aware of what features of System.Drawing they can safely use. I would rather try to have features of the library work the same across platforms as best I can.

If you want the features that not cross platform supported you need to go on Nuget and Download it, so i think it is fine then to use size, Rec...

**Comment by ChrisDill** [comment]
Could possibly get it to work with the types but I don't see enough benefit to taking on the dependency at this stage. I might reconsider in the future when making other breaking changes but for now I think the focus should be making the current types easier to use.

**Comment by MrScautHD** [comment]
> Could possibly get it to work with the types but I don't see enough benefit to taking on the dependency at this stage. I might reconsider in the future when making other breaking changes but for now I think the focus should be making the current types easier to use.

I mean, using Vector2 for a int Size is very bad...

**Comment by ChrisDill** [comment]
What do you mean exactly? Vector2 is used to match the same type raylib uses...

**Comment by MrScautHD** [comment]
> 

well, ok...

**Comment by MrScautHD** [comment]
but does they get casted then to int?

(so is it really working as a float?)

**Comment by spec-chum** [comment]
I vote against this, sorry - the original RL has floats for Rectangle, and we should keep as close to upstream as possible.

That said, there is [RectangleF](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.rectanglef?view=net-6.0), which can even take a `Vector4` as input, and doing an implicit conversion to the current `Rectangle` shouldn't cause any issues.

**Comment by n77y** [comment]
> I vote against this, sorry - the original RL has floats for Rectangle, and we should keep as close to upstream as possible.
> 
> That said, there is [RectangleF](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.rectanglef?view=net-6.0), which can even take a `Vector4` as input, and doing an implicit conversion to the current `Rectangle` shouldn't cause any issues.

I agree, I think `System.Drawing.RectangleF` would be the ideal alternative to `Raylib_cs.Rectangle`. I personally would prefer it as well. The main issue I can potentially see being problematic is the naming mismatch.

Also worth noting that is has a handy [`implicit operator`](https://learn.microsoft.com/en-us/dotnet/api/system.drawing.rectanglef.op_implicit?view=net-6.0) so you can pass `System.Drawing.Rectangle` into a method with param type `RectangleF` and it should work just fine.

**Comment by n77y** [comment]
> but does they get casted then to int?
> 
> (so is it really working as a float?)

When calling `DrawRectanglePro` the rect coordinates are used to set vertex positions (as floats) so floating values are the most sensible approach.

https://github.com/raysan5/raylib/blob/32b54be5cbd9eb77fc36a4c044dce69c5640a26a/src/rshapes.c#L798-L808

**Comment by spec-chum** [comment]
> > but does they get casted then to int?
> > (so is it really working as a float?)
> 
> When calling `DrawRectanglePro` the rect coordinates are used to set vertex positions (as floats) so floating values are the most sensible approach.
> 
> https://github.com/raysan5/raylib/blob/32b54be5cbd9eb77fc36a4c044dce69c5640a26a/src/rshapes.c#L798-L808

To be fair, int to float is implicit, a float can represent any int - it's the other way you need to worry about.

**Comment by MrScautHD** [comment]
So lets do a vote


Who is for it that reacts with 👍

If you not for it react with 👎

**Comment by MrScautHD** [comment]
Well you guys won then!
