### ISSUE TITLE
[Bug] Fix names in structs!

### ISSUE THREAD

**Issue by MrScautHD** [ChrisDill/Raylib-cs#163]
Before submitting a new issue, please verify and check:

 - [x] The issue is specific to Raylib-cs and not raylib
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of Raylib-cs

### Issue description

Hello, i saw variable names that not agree with the C# rules.

Example:

Yours:
```cs
    public partial struct Transform
    {
        /// <summary>
        /// Translation
        /// </summary>
        public Vector3 translation;

        /// <summary>
        /// Rotation
        /// </summary>
        public Quaternion rotation;

        /// <summary>
        /// Scale
        /// </summary>
        public Vector3 scale;
    }
```

How it should look like:

```cs
    public partial struct Transform
    {
        /// <summary>
        /// Translation
        /// </summary>
        public Vector3 Translation;

        /// <summary>
        /// Rotation
        /// </summary>
        public Quaternion Rotation;

        /// <summary>
        /// Scale
        /// </summary>
        public Vector3 Scale;
    }
```

### Environment
*Raylib-cs

**Comment by MrScautHD** [comment]
@ChrisDill What you think about it?

**Comment by ChrisDill** [comment]
Open to trying this out and Transform seems like a good place to start with this.

**Comment by 9ParsonsB** [comment]
This will require all existing code using this struct to be updated. Are we going to limit this to the next major release?

**Comment by MrScautHD** [comment]
Its not that big deal, but lets talk to chrisdill

**Comment by ChrisDill** [comment]
@MrScautHD It is a breaking change so I agree with @9ParsonsB that it should go into a major release. Considering creating a separate branch to track and test breaking changes like this.

**Comment by MrScautHD** [comment]
> @MrScautHD It is a breaking change so I agree with @9ParsonsB that it should go into a major release. Considering creating a separate branch to track and test breaking changes like this.

ok, yea then lets do a own branch for it.

**Comment by MrScautHD** [comment]
Can you create one, so we can do pull requests for it?

**Comment by ChrisDill** [comment]
@MrScautHD Done, dev branch created. Can you fix the conflicts then I can merge it in.

**Comment by MrScautHD** [comment]
thx, yea sure

**Comment by MrScautHD** [comment]
> @MrScautHD Done, dev branch created. Can you fix the conflicts then I can merge it in.

I resolved the conflicts, i even made a few mistakes by the names that are fixed now to :)

**Comment by MrScautHD** [comment]
@ChrisDill is there anything that need todo?

**Comment by ChrisDill** [comment]
I have added a dev branch to the examples to test the changes and check for any issues. Looks good so far!

Nothing specific at the moment. Thinking about other design changes I may make but have not decided yet.

**Comment by MrScautHD** [comment]
> I have added a dev branch to the examples to test the changes and check for any issues. Looks good so far!
> 
> Nothing specific at the moment. Thinking about other design changes I may make but have not decided yet.

i made some checkes too, and it looks fine for me.

**Comment by Shadowblitz16** [comment]
Yes Please!
I always hated how raylib-cs didn't use C# naming conventions.

**Comment by MrScautHD** [comment]
I saw you renamed the Rlgl methods what about we remove from the methods the rl

**Comment by ChrisDill** [comment]
@MrScautHD Initially I changed them back to get it working with the examples. Now that is done we can try removing the prefix and see how that looks. Needs the EntryPoint to be set so the name can be different.

**Comment by MrScautHD** [comment]
> @MrScautHD Initially I changed them back to get it working with the examples. Now that is done we can try removing the prefix and see how that looks. Needs the EntryPoint to be set so the name can be different.

yea i forgot about the EntryPoint...

Instead of:
```cs
[DllImport(nativeLibName, CallingConvention = CallingConvention.Cdecl)]
public static extern void rlEnd();
 ```
 
 Lets do:
 ```cs
[DllImport(nativeLibName, EntryPoint = "rlEnd", CallingConvention = CallingConvention.Cdecl)]
public static extern void End();
```

**Comment by MrScautHD** [comment]
If you agree with that i could do that for the full class

**Comment by MrScautHD** [comment]
```cs
        // GL blending functions/equations
        public const int RL_FUNC_ADD = 0x8006;
        public const int RL_MIN = 0x8007;
        public const int RL_MAX = 0x8008;
        public const int RL_FUNC_SUBTRACT = 0x800A;
        public const int RL_FUNC_REVERSE_SUBTRACT = 0x800B;
        public const int RL_BLEND_EQUATION = 0x8009;
        public const int RL_BLEND_EQUATION_RGB = 0x8009;
        public const int RL_BLEND_EQUATION_ALPHA = 0x883D;
        public const int RL_BLEND_DST_RGB = 0x80C8;
        public const int RL_BLEND_SRC_RGB = 0x80C9;
        public const int RL_BLEND_DST_ALPHA = 0x80CA;
        public const int RL_BLEND_SRC_ALPHA = 0x80CB;
        public const int RL_BLEND_COLOR = 0x8005;
```

Should we remove the RL before the names to?

**Comment by MrScautHD** [comment]
it would looks way cleaner... i removed it with my latest pull request.

**Comment by MrScautHD** [comment]
And i would suggest to rename the `Raylib_cs` namespace to `Raylib`

**Comment by MrScautHD** [comment]
Fixed https://github.com/ChrisDill/Raylib-cs/commit/23ed54cc2455f6527be72ff86f90f2b8bdc8c5af
