### ISSUE TITLE
[Feature] Add custom build flags (like custom OpenGL version...)

### ISSUE THREAD

**Issue by MrScautHD** [ChrisDill/Raylib-cs#169]
Before submitting a new issue, please verify and check:

 - [x] The issue is specific to Raylib-cs and not raylib
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of Raylib-cs

### Issue description

I would love to see this feature in Raylib-cs, then we would have ANGLE support and it would possible to run a new or older version of OpenGL.

```cs
public static void SetOpenGLVersion(GlVersion version) {
      // Impliment it here
      // I would suggest doing a variable in the build that can be changed with code, so we can switch the Raylib.dll with the right OpenGL version.
}
```

### Environment
OpenGL

**Comment by ChrisDill** [comment]
Would require modifying raylib as currently opengl versions are selected with compile flags. Though we are considering custom builds in #118 so this could maybe be looked at with that.

**Comment by MrScautHD** [comment]
> Would require modifying raylib as currently opengl versions are selected with compile flags. Though we are considering custom builds in #118 so this could maybe be looked at with that.

so is that already planned?

**Comment by ChrisDill** [comment]
Nothing specifically planned at the moment.

**Comment by MrScautHD** [comment]
> 

So would that possible easy?

I mean we could just switch the dll or not?

**Comment by ChrisDill** [comment]
Some changes might only involve changing flags. However selecting the opengl version at runtime means modifying raylib to support this which means making a fork and keeping it in sync with raylib.

**Comment by MrScautHD** [comment]
> 

well, doing just 5 .dll files would work fine too or? every with a diffrent GL version.

**Comment by MrScautHD** [comment]
but does they get casted then to int?

**Comment by ChrisDill** [comment]
That would not work because there are 6 different opengl configs for raylib. With 5 platform folders in runtimes that would be 30 different libraries greatly increasing the size of the nuget package and complexity of library loading. At that point it is better for users to build a custom version of raylib instead.

**Comment by MrScautHD** [comment]
> That would not work because there are 6 different opengl configs for raylib. With 5 platform folders in runtimes that would be 30 different libraries greatly increasing the size of the nuget package and complexity of library loading. At that point it is better for users to build a custom version of raylib instead.

oh well

**Comment by MrScautHD** [comment]
> That would not work because there are 6 different opengl configs for raylib. With 5 platform folders in runtimes that would be 30 different libraries greatly increasing the size of the nuget package and complexity of library loading. At that point it is better for users to build a custom version of raylib instead.

Is it hard todo? Because i has no idea how to do that 😅

**Comment by MrScautHD** [comment]
So... How you want ro implement it?

**Comment by 9ParsonsB** [comment]
@MrScautHD Have a look at the SQLite, SQLitePCL, & SQLitePCLRaw Nuget Packages

**Comment by MrScautHD** [comment]
sad :/

**Comment by MrScautHD** [comment]
so it is not comming with the Build system?

**Comment by ChrisDill** [comment]
The local build is to try and make it easier to customize raylib but by default won't include the change to set it at runtime as it is requires a lot of changes to rlgl. The local build should allow changing it at compile time though.

**Comment by MrScautHD** [comment]
No, Just the example above was the first idea it should just possible to set it before running it

**Comment by MrScautHD** [comment]
But fine the pull reuquest is still open so it is coming :)

Btw when next nuget update 😅
