### ISSUE TITLE
LoadTexture with path containing special characters not working

### ISSUE THREAD

**Issue by SebLague** [ChrisDill/Raylib-cs#172]
Hi, thanks for the great bindings! I'm currently running into an issue trying to load a texture when the path contains special characters such as 'ã'.
Here is my test code:
```
string path = "C:\\Users\\sebas\\Desktop\\chãrtest\\Pieces.png";
piecesTexture = Raylib.LoadTexture(path);
```
This works fine if the path does not contain the special character. Am I doing something wrong, or is there any work-around for this?
Using windows 10 and latest version of raylib/raylib-cs.

**Comment by Firestorm-253** [comment]
> what error printed to the console?

[with path containing diacritics](https://github.com/SebLague/Chess-Challenge/issues/247)

**Comment by anggape** [comment]
after trying to reproduce this bugs,
seems like raylib cant handle utf8 characters on windows, [here](https://github.com/ChrisDill/Raylib-cs/blob/10c0a6dd91db6a311f91ca400ffa305e8408a61e/Raylib-cs/types/native/UTF8Buffer.cs#L16C4-L16C4) how raylib-cs convert c# string to c char* , file will load properly if you replace `StringToCoTaskMemUTF8` with `StringToHGlobalAnsi` but you will get `AccessViolationException`, for now you can replace `LoadTexture` with `Raylib.LoadTextureFromImage(Raylib.LoadImageFromMemory(".png", FILE_BYTES))`

**Comment by SebLague** [comment]
Thank you @anggape LoadImageFromMemory seems to have done the trick!
