### ISSUE TITLE
[Feature] Add a string method for `OpenURL` and `SetGamepadMappings`

### ISSUE THREAD

**Issue by MrScautHD** [ChrisDill/Raylib-cs#178]
Before submitting a new issue, please verify and check:

 - [x] The issue is specific to Raylib-cs and not raylib
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of Raylib-cs

### Issue description

Hello, i saw by the methods `OpenURL` and `SetGamepadMappings` that there is just a method that takes `sbyte*` i would suggest to do a second method with a string value.

And i found another thing, you could use instead of try/finally:

### You use:
```cs
    public static unsafe int MeasureText(string text, int fontSize)
    {
      UTF8Buffer utF8Buffer = text.ToUTF8Buffer();
      try
      {
        return Raylib.MeasureText(utF8Buffer.AsPointer(), fontSize);
      }
      finally
      {
        utF8Buffer.Dispose();
      }
    }
```
    
### What i suggest:
```cs
    public static unsafe int MeasureText(string text, int fontSize)
    {
        using (UTF8Buffer buffer = text.ToUTF8Buffer())
        {
            return Raylib.MeasureText(buffer.AsPointer(), fontSize);
        }
    }
 ```
    
### What i suggest (smallest):
```cs
    public static unsafe int MeasureText(string text, int fontSize) {
        using UTF8Buffer buffer = text.ToUTF8Buffer();
        return Raylib.MeasureText(buffer.AsPointer(), fontSize);
    }
```

**Comment by MrScautHD** [comment]
Let me know if you like my idea so i doing a PR.

**Comment by 9ParsonsB** [comment]
We are more then happy to accept pull requests, though we already use your suggested method:

https://github.com/ChrisDill/Raylib-cs/blob/master/Raylib-cs/types/Raylib.Utils.cs#L886

**Comment by MrScautHD** [comment]
> We are more then happy to accept pull requests, though we already use your suggested method:
> 
> https://github.com/ChrisDill/Raylib-cs/blob/master/Raylib-cs/types/Raylib.Utils.cs#L886

ohhh, if i download it on nuget it doing it like that.... lol

**Comment by MrScautHD** [comment]
I wanna create laiter a pull for the string value

**Comment by MrScautHD** [comment]
Merged: https://github.com/ChrisDill/Raylib-cs/pull/180
