### ISSUE TITLE
Can not init a window in MacOS

### ISSUE THREAD

**Issue by Ahzed11** [ChrisDill/Raylib-cs#19]
**Describe the bug**
Can't Init a Window on MacOS. (System.DllNotFoundException)

**To Reproduce**
Install the Raylib-cs Nuget Package through Visual Studio Mac and write this piece of code.
```
using System;
using static Raylib.Raylib;

namespace myGame
{
    class MainClass
    {
        const string GAME_NAME = "My game";
        public static void Main()
        {
            int width = 800;
            int height = 400;
            InitWindow(width, height, GAME_NAME);
            SetTargetFPS(60);
        }
    }
}
```

**Expected behavior**
A window should be Initialized with the chosen size and title.

**Details**
System.DllNotFoundException: raylib
  at at (wrapper managed-to-native) Raylib.Raylib.InitWindow(int,int,string)
  at myGame.MainClass.Main () [0x0000d] in /Users/myname/Documents/Programmation/C#/myGame/myGame/Program.cs:13

**Desktop**
 - OS: MacOS Mojave 10.14.1

**Comment by ChrisDill** [comment]
I have only tested on windows so I am not sure.  I think raylib needs to be built as a .dylib to work on mac.
https://stackoverflow.com/questions/40878149/is-it-possible-to-use-dlls-with-visual-studio-mac
I cannot do it myself so thats why its not yet supported.

**Comment by LetsCode-Angus** [comment]
Yeah @ChrisDill @Ahzed11, It needs to be built as a .dylib to be compatible, this would require you to build it yourself, using the Xcode GCC implementation
