### ISSUE TITLE
Combine ChrisDill/Raylib-cs-Examples repository

### ISSUE THREAD

**Issue by anggape** [ChrisDill/Raylib-cs#191]
Before submitting a new issue, please verify and check:

 - [X] The issue is specific to Raylib-cs and not raylib
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of Raylib-cs

### Issue description
every time i made change to this repository i need to do multiple step just to test if my change is working
for example:
- made some change to the code
- run `dotnet pack` on this repository
- open https://github.com/ChrisDill/Raylib-cs-Examples repository
- delete raylib-cs nuget cache
- restore nuget package locally using previous build
- check if my change working properly

if we combine the examples repository this can be simplified into
- made some change
- run examples
- check if my change working properly

**Comment by ChrisDill** [comment]
Considering merging them back in as I agree it has made it harder to test. Initially want to try out your changes in #186 with Raylib-cs-Examples so it uses Raylib-cs directly instead of using the nuget package.

**Comment by ChrisDill** [comment]
@anggape Looking more into it I decided to go ahead with merging the main examples project back in. Next I want to get examples working with the local build to complete #186.
