### ISSUE TITLE
InputGamepad demo not working

### ISSUE THREAD

**Issue by xX-Squic-Xx** [ChrisDill/Raylib-cs#196]
For my graduation work, I have to use controller support. Unfortunately, the example for the latter is not functional and I find myself in trouble. I use the Raylib library on Windows 10 and I use a Gembird JPD-UDV-01 controller

**Comment by ChrisDill** [comment]
There are issues with the gamepad example being worked at the moment in #195. If the issue still exists outside the example then it may be a issue with the mappings in raylib. I don't have that controller myself so I am not able to test this issue.

**Comment by ChrisDill** [comment]
@xX-Squic-Xx Any update on this issue?
