### ISSUE TITLE
Use the enums!

### ISSUE THREAD

**Issue by rfaa00** [ChrisDill/Raylib-cs#20]
**Is your feature request related to a problem? Please describe.**
Many of the raylib bindings use e.g. an int as input parameter while still having a corresponding enum that doesn't seem to be used anywhere. Is this intentional?

```
enum KeyboardKey {...} // not used anywhere?
public static extern bool IsKeyPressed(int key);
```

**Describe the solution you'd like**
A method that uses the enum and simply casts the value to an int(or the appropriate type) and then calls the raylib method.
Perhaps even mark the raylib method as private to minimize confusion?

```
public static extern bool IsKeyPressed(KeyboardKey key) => IsKeyPressed((int)key);
```

If this seems like a good idea I'd be willing to create a pull request :)

**Comment by ChrisDill** [comment]
Thanks for the suggestion! Its something im working on.

Bindings started using int to try to match existing examples. More enums were added later but I couldn't find a way to implictly cast them so I left it for a while. 

I think I should deprecated the old constants that the enums replace anyway so it might be better to test using them directly.
