### ISSUE TITLE
Make fields in 'RenderBatch' struct public

### ISSUE THREAD

**Issue by Tangenten** [ChrisDill/Raylib-cs#202]
- [X] The issue is specific to Raylib-cs and not raylib
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of Raylib-cs

fields are private, so cant do much with this struct. RenderBatch seems useful as a high performance way to build up a drawcall. Something im trying to optimize right now.

https://github.com/ChrisDill/Raylib-cs/blob/master/Raylib-cs/types/RenderBatch.cs

**Comment by ChrisDill** [comment]
Thanks! RenderBatch needed review and has been updated to fix this issue.
