### ISSUE TITLE
missing Vector3 definition?

### ISSUE THREAD

**Issue by danielchasehooper** [ChrisDill/Raylib-cs#204]
Before submitting a new issue, please verify and check:

 - [X] The issue is specific to Raylib-cs and not raylib
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of Raylib-cs

### Issue description

I'm not able to use Vector3, it doest look like it's declared in the bindings anywhere?

### Environment

macOS 13.6, Raylib-cs 4.5.0.4
```
$ dotnet --list-runtimes
Microsoft.AspNetCore.App 7.0.0 [/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 7.0.0 [/opt/homebrew/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App]
$ dotnet --list-sdks
7.0.100 [/opt/homebrew/Cellar/dotnet/7.0.100/libexec/sdk]
```

### Issue screenshot
![Screenshot 2023-10-15 at 6 01 53 PM](https://github.com/ChrisDill/Raylib-cs/assets/1472250/7d182793-0262-4dc8-9b62-1aa76b77bbaf)

### Code example

```
namespace HelloWorld;

using Raylib_cs;
using static Raylib_cs.Raylib;
using static Raylib_cs.Raymath;

class Program
{
    public static void Main()
    {
        InitWindow(800, 480, "Hello World");

        Camera3D camera = new();
        camera.position = new Vector3(50.0f, 50.0f, 50.0f);
}
}
```

**Comment by 9ParsonsB** [comment]
`Vector3` is defined in `System.Numerics`

**Comment by danielchasehooper** [comment]
@9ParsonsB Thank you! 

I'm new to the c# world - in the future, how should I go about finding where things are defined? Coming from C, I would typically grep the standard library/3rd party headers, I'm not sure what the equivalent would be for dotnet.
