### ISSUE TITLE
FormatText function missing

### ISSUE THREAD

**Issue by Lathuys** [ChrisDill/Raylib-cs#21]
In raylib v2.0.0 quick reference card there is a FormatText function described like this:
const char *FormatText(const char *text, ...); // Formatting of text with variables to 'embed'
and here it is missing

**Comment by raysan5** [comment]
@Lathuys `FormatText()` has been renamed lately to `TextFormat()` to keep consistency with a bunch of text management functions... actually most of those functions are a C repkacement for C# String methods. Maybe raylib-cs should use those methods instead...

**Comment by ChrisDill** [comment]
It is using string.Format instead at the moment. It is not exactly the same so it might be a good idea to change it.
