### ISSUE TITLE
Add a managed version as a separated package

### ISSUE THREAD

**Issue by Odex64** [ChrisDill/Raylib-cs#214]
Resuming the #121 issue and the #188 pull request, I would love to have a managed version of Raylib.
Currently there has been some discussion whether to create a managed version of Raylib, ultimately the decision was to keep this binding as it is and let the users create their own frameworks around it.

While I agree about keeping this binding as minimal as possible, I still propose to make a managed version with some additional features as a standalone package. In this way we get all the advantages of managed classes without altering the binding.

If you agree I'm willing to work on a managed version in order to achieve a simple and neat API similar to FNA or MonoGame does.

**Comment by ChrisDill** [comment]
@Odex64 I decided it was out of scope for this repository as it is easier to maintain and more flexible since there are multiple ways you can approach a managed version.

That said feel free to work on one in your own repository and make your own standalone package for it. :smile:
