### ISSUE TITLE
2.5 plan

### ISSUE THREAD

**Issue by ChrisDill** [ChrisDill/Raylib-cs#22]
Plan to update project for raylib 2.5.

- [ ] Reduce unsafe with features like Span.
- [x] Support for mac and linux builds of raylib(.so .dylib) #19.
- [x] Decide how to support modules such as physac.
- [ ] Improve generator so it can regenerate current bindings.
- [x] Highlight differences more clearly. #21 TextFormat etc.

**Comment by ChrisDill** [comment]
Module issues
1. Currently uses a custom build system since modules are optional and not all included by default(raygui).
2. Cannot modify data stored in c since it is copied. In physac it stores PhysicsBodyData and returns a pointer to it. From c# it is copied so changes have no effect on the simulation.

Maybe port fully to c# instead or modify them so they work easier.
Unsure how to go about solving this.

**Comment by raysan5** [comment]
Hi @ChrisDill, actually most of the key modules are included by default, there are only some special cases:
 - [raudio](https://github.com/raysan5/raylib/blob/master/src/raudio.c) module can be skipped with compilation flag `INCLUDE_AUDIO_MODULE`.
 - [easings.h](https://github.com/raysan5/raylib/blob/master/src/easings.h) This module is independent of raylib, just a handy easings library, mostly intended for user side.
 - [raymath.h](https://github.com/raysan5/raylib/blob/master/src/raymath.h), compiled with raylib but most functionality is not exposed by default.
 - [raygui](https://github.com/raysan5/raygui) IMGUI library build over raylib, designed to be somewhat independent of the underlying engine, just requires some input/drawing function hooks.
 - [physac](https://github.com/victorfisac/Physac) Independent physics library for raylib, not directly supported by me...

About the comented issues, not sure what to do with it...

**Comment by ChrisDill** [comment]
@raysan5 I guess I mean accessible from c# by default. Edited the description. Most of the modules work when exported across. I think I might try a physac port to compare.

**Comment by ChrisDill** [comment]
I have looked more into modules and I think porting some of them makes the most sense for now. Using a custom build has been causing issues for cross platform support.

**Comment by ChrisDill** [comment]
Update: Removing custom built libraries. 

At first I thought having one you can install would save people time but after trying that for a while I ended up using a custom build in my own project. I found that including all modules by default is not the best option in reality and it works out better to leave that up to the user.

**Comment by ChrisDill** [comment]
Preparing for next raylib release here #33.
