### ISSUE TITLE
Suggestion: pin GitHub Action to most recent LTS version of Ubuntu

### ISSUE THREAD

**Issue by njlr** [ChrisDill/Raylib-cs#222]
The binary Nuget package will not work with the most recent LTS release of Ubuntu (`20.04`) since the GitHub Action is on "latest" (`22.04`), which has a later version of GLib C. 

Moving the GitHub Action to the _latest LTS_ would give wider compatibility, and not require end-users to be on an OS version without long-term support.

The change would be to replace `runs-on: ubuntu-latest` with `runs-on: ubuntu-20.04`.

Would a PR be accepted?

**Comment by ChrisDill** [comment]
Good idea! A PR would be accepted for this.

**Comment by njlr** [comment]
Thanks!

Any chance a patch release can be triggered?
