### ISSUE TITLE
[BUG] `DllImport` makes problems on some pcs

### ISSUE THREAD

**Issue by MrScautHD** [ChrisDill/Raylib-cs#226]
Before submitting a new issue, please verify and check:

 - [x] The issue is specific to Raylib-cs and not raylib
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of Raylib-cs

### Issue description
Hello, I'm encountering an issue with the .dll importer in C#. It's a bit puzzling because it seems to work on some PCs but not others. On my main development machine, everything runs smoothly. However, on my test PC, I consistently encounter an error. Interestingly, on my sister's PC, it works flawlessly. It's quite perplexing, but I found that replacing the .dll with the original raylib one resolves the issue on any PC.

### Environment

OpenGL: `3.3`
Raylib-cs: `6.0`
Raylib: `5.0`

### Issue screenshot
![image](https://github.com/ChrisDill/Raylib-cs/assets/65916181/c7c5f115-a091-480d-89b7-5ca97222936e)

**Comment by ChrisDill** [comment]
From what you said in discord it is a windows bug which started working for you after setting up jetbrains rider. Closing the issue but feel free to add further details here that might help anyone else who runs into this.
