### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by Bambofy** [ChrisDill/Raylib-cs#23]
Loading the library causes a huge memory leak on running the default project.

**Comment by msmshazan** [comment]
Which operating system?

**Comment by Bambofy** [comment]
http://richardbamford.io/dmp/958M0MFHvl.mp4

**Comment by ChrisDill** [comment]
Try this in your loop.
```csharp
BeginDrawing();
ClearBackground(Color.SKYBLUE);
EndDrawing();
```

**Comment by Bambofy** [comment]
Works! thanks :) awesome library.

**Comment by msmshazan** [comment]
@Bambofy please close the issue if the problem is solved :)
