### ISSUE TITLE
[Feature] Repackage Raylib-cs.

### ISSUE THREAD

**Issue by MrScautHD** [ChrisDill/Raylib-cs#230]
Before submitting a new issue, please verify and check:

 - [x] The issue is specific to Raylib-cs and not raylib
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of Raylib-cs

### Issue description

Greetings,

I propose repackaging Raylib-cs to incorporate significant features currently absent in version 5.0. These include support for new animation formats and the integration of the Glad class into the .dll, enabling the utilization of OpenGL with Raylib-cs. Regrettably, the forthcoming update is not expected in the immediate future.

**Comment by ChrisDill** [comment]
The Raylib-cs package is for official releases of raylib. If the features are not available in raylib 5.0 then you will need to build the version of raylib that has the features yourself to use them.

**Comment by 9ParsonsB** [comment]
@MrScautHD Is this in relation to [this conversation](https://discord.com/channels/426912293134270465/427518168995725317/1208114863667282011)?

If so, then what you are looking for is for Raylib-cs to support the development releases of raylib

To start this, change the `TargetRaylibTag` in `Raylib.cs/Build.props` and update/implement any changes in `Raylib.cs/interop/raylib.cs`
