### ISSUE TITLE
Add wayland support?

### ISSUE THREAD

**Issue by 990xan** [ChrisDill/Raylib-cs#234]
Before submitting a new issue, please verify and check:

 - [X] The issue is specific to Raylib-cs and not raylib
 - [X] I checked there is no similar issue already reported
 - [N/A] My code has no errors or misuse of Raylib-cs

### Issue description

Is it currently possible to enable raylib's wayland support? Doing this with the C version involves setting a build flag, is there any chance of getting some way to enable this in the C# port?

### Environment

Applicable to Linux computers running the wayland display server.

### Issue screenshot

N/A, but see https://github.com/raysan5/raylib/issues/414

### Code example

N/A

**Comment by MrScautHD** [comment]
Yep you can set flags but sadly just with the github project and not with the nuget one
