### ISSUE TITLE
Transparrent textures on planes not transparrent?

### ISSUE THREAD

**Issue by Bambofy** [ChrisDill/Raylib-cs#24]
<img width="400" alt="RaylibTesting_0ef4eTvQY7" src="https://user-images.githubusercontent.com/1304898/54145123-37abde80-4425-11e9-8da0-0969cc3536d2.png">

Here, the texture on the sword plane's edge is transparent, but the plane mesh/model behind is cut off to the clear color. How can i resolve this?

**Comment by Bambofy** [comment]
Actually the sword's transparent works fine, but the alpha on this image isn't working?
Might be something to do with the CropImage()?

![bomb_party_v4](https://user-images.githubusercontent.com/1304898/54145391-d6383f80-4425-11e9-97e3-72c3069fab2f.png)

**Comment by Bambofy** [comment]
after more experiment i have found that it's something to do with the depth testing?

**Comment by Bambofy** [comment]
Ok i have found a hacky solution by discarding any fragments that are transparrent.

"
in vec2 fragTexCoord;
in vec4 fragColor;
in vec3 fragNormal;
in vec3 fragPosition;

uniform sampler2D texture0;
uniform vec4 colDiffuse;

out vec4 finalColor;

void main()
{
    vec4 texturePixel = texture2D(texture0, fragTexCoord);
    if (texturePixel.w < 0.5)
    {
        discard;
    }
    finalColor = texturePixel; 
}";

**Comment by ChrisDill** [comment]
Not sure if this is a issue with the binding code or not. Please refer to the [author's project repo](https://github.com/raysan5/raylib) and ask there. If it is then open a new issue here with further details.
