### ISSUE TITLE
ExportImageToMemory uses wrong return type

### ISSUE THREAD

**Issue by danilwhale** [ChrisDill/Raylib-cs#244]
Before submitting a new issue, please verify and check:

 - [x] The issue is specific to Raylib-cs and not raylib
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of Raylib-cs

### Issue description

Original declaration looks like: 
```c
RLAPI unsigned char *ExportImageToMemory(Image image, const char *fileType, int *fileSize);
```
where `unsigned char *` should be `byte*` and not `char*`, because C `char` is equal to C# `sbyte` and `unsigned char` is equal to `byte` 
https://github.com/ChrisDill/Raylib-cs/blob/502a583e076cf1595a12def81206be7f804002e5/Raylib-cs/interop/Raylib.cs#L1371

**Comment by ChrisDill** [comment]
Thanks, fixed!
