### ISSUE TITLE
Incorrect enum value for KeyboardKey.Menu

### ISSUE THREAD

**Issue by MontyHimself** [chrisdill/Raylib-cs#247]
The value for KeyboardKey.Menu is defined as 82, which overrides the value for KeyboardKey.R:
https://github.com/chrisdill/Raylib-cs/blob/383ec91e95bf337a8742a2d82d6860fa540619e7/Raylib-cs/types/Input.cs#L131

In upstream raylib.h it is set to 5:
https://github.com/raysan5/raylib/blob/d9c5066382615644137b4f65479c65c44820027a/src/raylib.h#L680

**Comment by chrisdill** [comment]
@MontyHimself The bindings are currently using raylib 5.0 where it is set to 82.
https://github.com/raysan5/raylib/blob/ae50bfa2cc569c0f8d5bc4315d39db64005b1b08/src/raylib.h#L676C58-L676C64
