### ISSUE TITLE
JPG Format not supported

### ISSUE THREAD

**Issue by Aktayr** [chrisdill/raylib-cs#256]
Hi Chris. I tried to load a jpg image but nothing displayed. And i have this message :
![testJpg](https://github.com/chrisdill/raylib-cs/assets/94566167/0617b970-2a64-48e5-bde4-29931eb5ca1f)

Could you help me please ?

**Comment by chrisdill** [comment]
JPG is not enabled by default so requires a manual installation with a custom build of raylib that enables it.
