### ISSUE TITLE
Raylib DLL's do not export necessary functions

### ISSUE THREAD

**Issue by LetsCode-Angus** [ChrisDill/Raylib-cs#26]
The most up to date raylib binaries do not contain the correct exports for certain core functions such as InitWindow(). This may require a native wrapper with the correct exports to be built into a new library.

Eg;
```C++
INTERNAL bool InitWindow(int width, int height, const char* title);
// should be wrapped with
bool __declspec(dllexport) InitWindow(int width, int height, const* title) {
        InitWindow(width, height, title);
}
```
This wrapper code could then be built against a static lib of raylib to result in a single, correctly built, dll file.

**Comment by ChrisDill** [comment]
InitWindow() should work with the current version of raylib. It should be exported with the RLAPI define. The native libraries in this project need to be reviewed.
