### ISSUE TITLE
New Feature Added in Raylib is Unavailable

### ISSUE THREAD

**Issue by DanielBClute** [chrisdill/raylib-cs#260]
### Issue description
This recently added feature in raylib is not available.
https://x.com/raysan5/status/1807124615992402323

**Comment by MrScautHD** [comment]
> ### Issue description
> This recently added feature in raylib is not available.
> https://x.com/raysan5/status/180712461599240232

Hi,
Because it is still on 5.0 but if you want to use the 5.1 dev build it yourself or use Raylib-Csharp.

**Comment by DanielBClute** [comment]
amazing -- heard!
