### ISSUE TITLE
Release a Raylib project with c# Railyb-cs

### ISSUE THREAD

**Issue by Rincevant** [chrisdill/raylib-cs#269]
Hello everyone,

This is not a real technical issue but i really need help plz.

I got an issue System.DllNotfoundException Unable to load DLL 'raylib'
![Capture d’écran 2024-09-05 212759](https://github.com/user-attachments/assets/255c35f9-e157-4502-9ce4-f38a7d97c8af)

But actually I did release the game with or without all dependencies dll such as .net and all AND there is in the same directory all dll required (i hope so...)

![Capture d'écran 2024-09-05 213045](https://github.com/user-attachments/assets/0c1668ef-8465-4e64-be3c-13e9d0e66ab1)

Also my goal here is to share my game with friend so i want sent them the exe with resources and they play thats all. No installation required i think.

Locally my game work well only when i try it on an other computer its not working

Thanks for help and I hope to find an easy tutorial to Realease a game c# with Raylib

**Comment by 9ParsonsB** [comment]
How did you install raylib-cs? If you use the NuGet package, this should be handled for you
What version of Raylib are you using? What version of Raylib-cs are you using?
Can you share your code?

**Comment by Rincevant** [comment]
Hello @9ParsonsB thanks for your answer.

Yes I used NuGet package in Visual studio.

![image](https://github.com/user-attachments/assets/f17be22b-3a4d-45a6-9b0e-5526e2e8a7ae)

![image](https://github.com/user-attachments/assets/ea832235-99b6-4a26-bb19-48ad67f3e776)

If im right Raylib-cs 6.0.0 and about just Raylib not sure its working like this

For execute and use Visual studio compil or with command dotnet build and dotnet run

**Comment by 9ParsonsB** [comment]
So you only have issue on release? Can you provide the release? How do you create a release? via `dotnet publish`? How are you executing it? What is your `OutputType` in your `.csproj`?

**Comment by Rincevant** [comment]
Hello again !

Good news I found what was wrong. Actually and it's maybe obvious for people anyway but you need C++ redristributable installed on you computer 

![image](https://github.com/user-attachments/assets/18d9c9ff-3225-4f4d-9186-7f993785a499)

With this and only this because I tried it on a brand new computer game is now running well. 

Thanks for helping :)
I close the ticket
