### ISSUE TITLE
Unable to find an entry point named 'InitPhysics' in DLL 'libraylib'

### ISSUE THREAD

**Issue by GoldenQubicle** [ChrisDill/Raylib-cs#27]
Running the demos with the latest 2.5 release and all of them are working fine except for the physics examples. These all throw the same unhandled exception on InitPhysics. 

```
Exception User-Unhandled
System.EntryPointNotFoundException: 'Unable to find an entry point named 'InitPhysics' in DLL 'libraylib'.'
  at Raylib.Raylib.InitPhysics()
   at physics_demo.Main() in C:\raylib\Raylib-cs\Examples\physac\physics_demo.cs:line 41
```
Tried a few things like setting exactspelling to false for the dll import, and adding a reference to the dll in the csproj file, but to no avail. 

I'm running the demos with the Test.NetCore app and using the **mingw** dll ( the msvc15 version threw the same EntryPointNotFound exception on ChangeDirectory(), which made it impossible to run any demo at all ).

**Comment by ChrisDill** [comment]
The examples need to be updated for 2.5. The extra modules such as physac also need improving. 

As for finding the functions, you need to build the physac implementation into the library. There are a few flags in the Makefile for doing this such as RAYLIB_MODULE_PHYSAC although they might not be exported yet.

**Comment by GoldenQubicle** [comment]
Ah I see thanks for clarifying. Bit of a shame but it leaves plenty to play around with. Thanks for these bindings!
