### ISSUE TITLE
Tutorial RAYLIB-CS export to web

### ISSUE THREAD

**Issue by dragonal42** [chrisdill/raylib-cs#270]
Hello, 

I can't find a tutorial for exporting a RAYLIB-CS project to the web. 
Is it possible to do it ? is it the same as Raylib for C/C++ ? 
Can you make one? 

Thank you

**Comment by 9ParsonsB** [comment]
Hi, we don't currently support web nor have any working examples. 
However there are forks of raylib-cs that got WASM working, see https://github.com/stanoddly/DotnetRaylibWasm

**Comment by dragonal42** [comment]
yes ! thanks a lot !

**Comment by dragonal42** [comment]
thanks a lot !
