### ISSUE TITLE
 Inquiry about Using raygui，rlgl and rres Extensions

### ISSUE THREAD

**Issue by Yajanan** [chrisdill/raylib-cs#274]
Hello Team,

I hope this message finds you well. 

How can I use raygui, rres, and other raylib extensions?

I'm excited about the potential of incorporating these extensions into my work and would greatly appreciate your guidance and support.

Thank you for your time and assistance. Looking forward to your response.

**Comment by JupiterRider** [comment]
Hey @Yajanan ,
maybe this helps you: #130
