### ISSUE TITLE
Work with Avalonia devs to impliment avalonia wrappers for raylib-cs

### ISSUE THREAD

**Issue by Shadowblitz16** [chrisdill/raylib-cs#280]
Before submitting a new issue, please verify and check:

 - [x] The issue is specific to Raylib-cs and not raylib
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of Raylib-cs

### Issue description

See here https://github.com/AvaloniaUI/Avalonia/issues/17719
I just think it would be cool to have a gui library other then imgui for raylib-cs

### Environment

Kubuntu 24.04

### Issue screenshot
NA

### Code example
NA

**Comment by chrisdill** [comment]
Would be interesting to see a wrapper for it but not something I am interested in working on myself.
