### ISSUE TITLE
Use System.Numerics instead of custom vector types

### ISSUE THREAD

**Issue by sbarisic** [ChrisDill/Raylib-cs#31]
It would be a wise idea to use System.Numerics for vector and matrix types, as it would be more compatible with other libraries. They're also SIMD accelerated, and marshalling them works fine.

**Comment by ChrisDill** [comment]
@sbarisic That sounds interesting though I don't plan to change the vector and matrix types at the moment. Ideally a feature like this would be optional for those who want it.

**Comment by ChrisDill** [comment]
I have looked into this feature but I am currently unsure on the best way to proceed.
I tried to use System.Numerics in a test project to see how what users need to do to switch to it.

1. Add using System.Numerics in every file that uses these types.

2. Change fields like .x, .y, .z etc to .X, .Y, .Z etc.

This is a pain to do especially in a larger project so I looked to see if there was a easier way to make this a optional/non breaking change.

The only possible solution I found is to wrap the System.Numerics types in my own types and provide properties for access. This "might" work but I feel that defeats the idea of it as you need to convert/access the type manually when using external code that uses System.Numerics.

Another possible concern is with the Matrix. I need to look into the ordering of the fields to see if conflicts with how the raylib Matrix works. I do not think it makes sense to add System.Numerics only for Vector types but not Matrices as that will just make things more confusing for new users.

**Comment by sbarisic** [comment]
The order of the matrix elements should match OpenGL as far as i know, for anything else it would be enough to just transpose them before doing calculations.

Another way to make this less painful is to add an implicit cast to/from System.Numerics vectors.

**Comment by sbarisic** [comment]
It would be possible to create a wrapper over System.Numerics types and use implicit casts to automatically return internal type, but that pretty much defeats the purpose and makes it slower.

**Comment by 9ParsonsB** [comment]
@ChrisDill I Wouldn't too much about adding/chaning `using`s in every file - I believe VS can do it now for you anyway.

**Comment by ChrisDill** [comment]
@sbarisic There is now a numerics branch for this feature. I discussed it with @9ParsonsB and we decided that keeping this feature compatible is not possible so it is being tested as a breaking change. So far Vector2, Vector3 and Vector4 have been replaced.

Matrix4x4 has a different layout but transposing the matrix works for going from the numerics layout to the raymath and vice versa. Because of this it makes more sense to keep the Matrix type and convert it as this makes the difference explicit.

**Comment by matej-zajacik** [comment]
I'm undecided on the switch to the standard `System.Numerics` types (not sure of the benefits), but as far as breaking changes go, that shouldn't be a problem, should you decide to make the switch. It takes just minutes, maybe tens of minutes to adjust a project.

**Comment by i3elj** [comment]
What should I do when using `DrawTextureRec`? it takes a int based Vector2 and there's no alternative that uses the x and y components separately like `DrawTexture`
