### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by drwharris** [ChrisDill/Raylib-cs#32]
My setup is a raspberry Pi 3b+ running Raspbian Buster.

On the Pi I have installed dotnet core 2.2 and can create, build and run the standard Console "Hello World" app.

I have downloaded the "raylib-2.5.0-Linux-i386.tar.gz" library and placed "libraylib.so.2.5.0" in the root of my source directory as libraylib.so. Ive added the following to my csproj file:

```
  <Content Include="libraylib.so">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
  </ItemGroup>
```

And can confirm that the file is copied to "bin/Debug/netcoreapp2.2".

I have copied the Binding directory into my project and run 

> dotnet run /p:AllowUnsafeBlocks=true

But I get the following error:

```
Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'raylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libraylib: cannot open shared object file: No such file or directory
   at Raylib.Raylib.InitWindow(Int32 width, Int32 height, String title)
   at Program.Main() in /home/pi/clock/Program.cs:line 10
```

Here is the content of the directory:

```
pi@clock0:~/clock/bin/Debug/netcoreapp2.2 $ ls -la
total 2424
drwxr-xr-x 2 pi pi    4096 Aug 26 16:42 .
drwxr-xr-x 3 pi pi    4096 Aug 26 14:25 ..
-rw-r--r-- 1 pi pi     425 Aug 26 16:42 clock.deps.json
-rw-r--r-- 1 pi pi   64512 Aug 26 16:42 clock.dll
-rw-r--r-- 1 pi pi    9240 Aug 26 16:42 clock.pdb
-rw-r--r-- 1 pi pi     194 Aug 26 16:42 clock.runtimeconfig.dev.json
-rw-r--r-- 1 pi pi     146 Aug 26 16:42 clock.runtimeconfig.json
-rw-r--r-- 1 pi pi 2380509 May 31 19:09 libraylib.so
```

I even put the file in /usr/lib:

```
pi@clock0:/usr/lib $ ls -la libr*
-rwxrwxrwx 1 root root 2380509 Aug 26 14:11 libraylib.so
```

Any idea's?

**Comment by ChrisDill** [comment]
I currently do not have a raspberry PI I to test. It depends where it is looking for the library. Look at the search paths at https://www.mono-project.com/docs/advanced/pinvoke/. Maybe it works like the linux search path?

**Comment by drwharris** [comment]
Yeah its just Linux, hence my statement about /usr/lib.

> Linux Shared Library Search Path
> From the dlopen(3) man page, the necessary shared libraries needed by the program are searched for in the following order:
> 
> 1. A colon-separated list of directories in the user’s LD_LIBRARY_PATH environment variable. This is a frequently-used way to allow native shared libraries to be found by a CLI program.
> 2. The list of libraries cached in /etc/ld.so.cache. /etc/ld.so.cache is created by editing /etc/ld.so.conf and running ldconfig(8). Editing /etc/ld.so.conf is the preferred way to search additional directories, as opposed to using LD_LIBRARY_PATH, as this is more secure (it’s more difficult to get a trojan library into /etc/ld.so.cache than it is to insert it into LD_LIBRARY_PATH).
> 3. /lib, followed by /usr/lib.

So guessing no ideas?

**Comment by ChrisDill** [comment]
Hmm. Check the architecture you are building for. Maybe try 64 bit instead although if it is not finding it then you need to debug what is is doing using the LD_DEBUG environment variable.

**Comment by drwharris** [comment]
Does your code require 64 bit? Raspbian is a 32bit OS.

I have tried LD_DEBUG and all it tells me it that i cant find the library including in /usr/lib which it definitely is in. Which makes me think maybe its an OS Architecture issue.

I might try installing Ubuntu Mate which is 64bit.

**Comment by ChrisDill** [comment]
It shouldn't require 64 bit. Is your dotnet core project set to target 32 bit?

**Comment by drwharris** [comment]
OK so I stuck with Raspbian and compiled raylib on the Pi and used that library and it all works fine.

So turns out that the runtime reports "DllNotFoundException" if it finds the library but it cant load it.
