### ISSUE TITLE
Using this with winforms or other gui libraries?

### ISSUE THREAD

**Issue by Shadowblitz16** [ChrisDill/Raylib-cs#34]
is it possible to use this with winforms or other .net gui libraries?

**Comment by ChrisDill** [comment]
There was a example for windows forms. I moved it to a gist [here](https://gist.github.com/ChrisDill/c2ca6a0ccf592c073a8d2aaeaa4adb7f) for now. Have not tested in a while but it is a good starting point. I am not sure about other gui libraries.

**Comment by Shadowblitz16** [comment]
thankyou I will take a look

**Comment by Shadowblitz16** [comment]
@ChrisDill is there a way to get a design time custom control for this?
```cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Raylib_cs;
using rl = Raylib_cs.Raylib;

namespace PureEditor.Controls
{
    public partial class RayControl : Control
    {
        private bool windowVisible  = false;
        private bool windowAttached = false;

        #region WinAPI Entry Points

        [DllImport("user32.dll")]
        private static extern IntPtr SetWindowPos(IntPtr handle, IntPtr handleAfter, int x, int y, int cx, int cy, uint flags);
        [DllImport("user32.dll")]
        private static extern IntPtr SetParent(IntPtr child, IntPtr newParent);
        [DllImport("user32.dll")]
        private static extern IntPtr ShowWindow(IntPtr handle, int command);

        #endregion

        public RayControl()
        {
            InitializeComponent();
        }

        protected override void OnVisibleChanged(EventArgs e)
        {
            base.OnVisibleChanged(e);
            windowVisible = Visible;
            if (!windowAttached)
            {
                rl.SetConfigFlags(ConfigFlag.FLAG_WINDOW_UNDECORATED);
                rl.InitWindow(800, 480, "Rayforms test");
                rl.SetTargetFPS(60);
                Task.Run(AttachWindow);
                windowAttached = true;
            }
        }

        async Task AttachWindow()
        {
            while (windowVisible)
            {
                IntPtr winHandle = rl.GetWindowHandle();
                Invoke(new Action(() =>
                {
                    SetWindowPos(winHandle, Handle, 0, 0, 0, 0, 0x0401 /*NOSIZE | SHOWWINDOW */);
                    SetParent(winHandle, Handle);
                    ShowWindow(winHandle, 1);
                    windowAttached = true;
                }));
                await Task.Delay(1);
            }
        }

        protected override void OnPaint(PaintEventArgs pe)
        {
            base.OnPaint(pe);
        }
    }
}
```
I am getting raylib dll not found exception when adding the control to the form

**Comment by ChrisDill** [comment]
I don't see how that code causes a dll not found exception. I would check that it can find raylib on its own without win forms first to make sure it loads correctly.

**Comment by Shadowblitz16** [comment]
huh odd I am using 3.1.5 and even normal raylib projects don't work.
I tried both x86 and x64

did something change with the project?

**Comment by ChrisDill** [comment]
It should work once it is able to load the library but support for framework is experimental so it requires a manual install. I suggest using winforms in dotnet core instead. See https://docs.microsoft.com/en-us/dotnet/core/porting/winforms for details.

**Comment by Shadowblitz16** [comment]
@ChrisDill winforms designer crashes and freezes up in .net core for me.
it also is very slow and does weird things like not allowing me to select controls forcing me to reopen the form every 2 control I add.

**Comment by ChrisDill** [comment]
In that case there is not much I can do. If you need winforms then framework + a manual install of raylib is needed. Though I suggest against it as it is experimental. Maybe report your issues with winforms in netcore and see if anyone else can help you fix it?
