### ISSUE TITLE
Please release this on nuget for visual studio 2019 community

### ISSUE THREAD

**Issue by Shadowblitz16** [ChrisDill/Raylib-cs#36]
please release this on nuget. I want to try out this library but I don't want to have to manually compile and link the libraries.

**Comment by ChrisDill** [comment]
I tried a nuget release although I felt I put it out too quickly and there were issues with it so I unlisted it. I may revisit it in the future when the I feel the project it is ready to try it again.

For now I recommend copying the bindings to your project and using a official raylib [release](https://github.com/raysan5/raylib/releases). You only need to compile yourself for extra modules like raygui or physac or if you change any of the config options.

**Comment by Shadowblitz16** [comment]
aww ok
