### ISSUE TITLE
embed raylib unmanaged c++ library in C# managed library

### ISSUE THREAD

**Issue by Shadowblitz16** [ChrisDill/Raylib-cs#38]
please embed the unmanaged c++ raylib library into a managed C# library.
I would recommend a .net framework and .net core version.

https://github.com/Fody/Costura.

this makes it easier on developers using your library and also allows people to static link their own libraries easier.

this would also make it easier to upload to nuget and overall make the users project and application cleaner.

**Comment by Shadowblitz16** [comment]
this might also get rid of the need to compile with unsafe if the Bindings are compiled into it.

**Comment by ChrisDill** [comment]
I don't know much about this. It says it is in maintenance mode and also mentions .NET Core 3 single file executable and assembly linking as alternatives.

I don't want to maintain seperate versions for framework and core.  That is why I moved the tests into one project with multiple targets. Also there was the announcement of [.NET 5](https://devblogs.microsoft.com/dotnet/introducing-net-5/) which says there will be one .NET moving forward.

I do agree it might make it easier for people to use the project at first although I found myself wanting to customize raylib for my needs instead.

**Comment by ChrisDill** [comment]
Update on this issue. I would like it to be easier to install and use the library. Current plan is to add a copy of the libraries of raylib for the release. I would consider the idea of embedding into a managed library if there is a up to date way of doing this.

**Comment by Shadowblitz16** [comment]
@ChrisDill reopen this please
you can embed the native dll using the Fody libraries
