### ISSUE TITLE
Loading OBJ File

### ISSUE THREAD

**Issue by StevenGann** [ChrisDill/Raylib-cs#39]
Maybe I'm being dense, but I'm attempting to load an OBJ file as done in one of the examples and and running into an error.

`Model model = LoadModel(@"monkey.obj");`

[monkey.zip](https://github.com/ChrisDill/Raylib-cs/files/4017989/monkey.zip)

Attached is the OBJ file I'm trying to load. LoadModel throws a System.ExecutionEngineException. I've attempted different paths, including a full absolute path, but I get the same error no matter what I've tried.

Any suggestions?

**Comment by ChrisDill** [comment]
Thanks for letting me know about this issue. Looks like it is another marshaling issue. This time with the Model. Looks similar to the problem with issue #9 with the arrays of custom structs.

There were some changes to raylib to reduce the need fixed arrays part although I am not sure on the best way to fix the rest.

The model struct for raylib 2.5:
```c
// Model type
typedef struct Model {
    Matrix transform;       // Local transform matrix

    int meshCount;          // Number of meshes
    Mesh *meshes;           // Meshes array

    int materialCount;      // Number of materials
    Material *materials;    // Materials array
    int *meshMaterial;      // Mesh material number

    // Animation data
    int boneCount;          // Number of bones
    BoneInfo *bones;        // Bones information (skeleton)
    Transform *bindPose;    // Bones base transformation (pose)
} Model;
```

The C# version:
```cs
    // Model type
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
    public struct Model
    {
        public Matrix transform;           // Local transform matrix
        public int meshCount;              // Number of meshes
        public Mesh[] meshes;              // Meshes array
        public int materialCount;          // Number of materials
        public Material[] materials;       // Materials array
        public IntPtr meshMaterial;        // Mesh material number
        public int boneCount;              // Number of bones
        public BoneInfo[] bones;           // Bones information (skeleton)
        public Transform[] bindPose;       // Bones base transformation (pose)
    }
```

To fix this I think I would need to change the array variables like `Mesh[] meshes` to a IntPtr or a unsafe pointer version. I am still undecided on this.

If I did make it use unsafe pointers directly then I could have a seperate safe layer over it. I don't want to add complexity to it if I don't have to though but this is a possible way forward.

Currently other structs use IntPtr instead so I will look into trying that.

**Comment by StevenGann** [comment]
Oh bother. That's rather inconvenient. Hopefully the next update will fix this along with mesh generation?

Any suggestions for the meantime? I can make do drawing primitive shapes for now, I guess.

**Comment by ChrisDill** [comment]
Primitive shapes should work okay as far as I know. I think the next version of raylib 2.6 should be released soon. I think I will wait until then to do a bigger update.

My focus at the moment is getting the examples updated and working so I can test and find these issues sooner. I guess I missed this issue with models as I have not used raylib in C# for 3D. I would also like to try continuous integration as well.

**Comment by ChrisDill** [comment]
@StevenGann Could you please check with the latest version of Raylib-cs if this is still a issue?

**Comment by StevenGann** [comment]
Sorry, just saw this.

OBJ file loading is working now. Thanks! I did encounter some OBJ files that cause a crash, but I'll investigate further and document that in another issue.
