### ISSUE TITLE
Add netcore support

### ISSUE THREAD

**Issue by ChrisDill** [ChrisDill/Raylib-cs#4]
Project has currently been tested with .net framework and mono. 
Using netcore could provide a better cross platform alternative.

Haven't used it before so any useful links would help. :)
Would involve supporting multiple project types.

**Comment by Gamerfiend** [comment]
When creating the Bindings project, did you select a template from the project creation? Such as Class Library ( Legacy Portable), Class Library (.NET Standard), Class Library( .NET Framework)?

**Comment by ChrisDill** [comment]
Update, bindings use .Net standard 2.0. Should allows bindings to be used in a netcore project. See commit https://github.com/ChrisDill/Raylib-cs/commit/4198ffb0bd34d3c1fa2513e99d27c517f7561fa9.

**Comment by ChrisDill** [comment]
There are now projects Test.NetCore and Test.NetCoreRT for netcore related support.

**Comment by raysan5** [comment]
Amazing work @ChrisDill! :D

**Comment by Lathuys** [comment]
So... how can I add this to my .NET Core project?

**Comment by ChrisDill** [comment]
@Lathuys The test projects are for running examples. Netcore support is almost complete although there is a issue with installing. See https://github.com/ChrisDill/Raylib-cs/issues/13
