### ISSUE TITLE
DllNotFoundException

### ISSUE THREAD

**Issue by uSources** [ChrisDill/Raylib-cs#40]
Hi,

I have read the README.MD in detail, I have downloaded from the GIT of raylib the release for windows x64 bits and windows x32 both msvc15.

The dll that is in the bin folder, I have copied it in a multitude of parts because nowhere has he achive to find the DLL.

I have copied it to system32
I have copied it to system
In the root of the project
In the root of the executable project

And there is no way to find the DLL

Im using Visual Studio 2019

Could you please help me?

Thank you

**Comment by ChrisDill** [comment]
There are different reasons why it might not find the dll. I assume you have looked through https://www.mono-project.com/docs/advanced/pinvoke/.  My bindings look for raylib so on windows it should look for raylib.dll.

Which dll are you trying to load? Check the architecture of the dll matches your C# project. E,g 64bit should match a 64bit C# project etc.

Hope this helps.

**Comment by uSources** [comment]
Hi, yes i read Windows section on https://www.mono-project.com/docs/advanced/pinvoke/.  on webpage.
Im trying several configuration to run the proyect witch includes Debug AnyCPU ( use raylib 32 bits)
and Debug x64 (uses raylib 64 bits).

I copy at exe output folder and C:/Windows/System32

And nothing happens always says DLLNotFound Exception

Im despairing :(

**Comment by uSources** [comment]
I didn´t give up and finally got a solution.

I didn´t add the DLL in the correct way to the VS solution.

Here I leave a response from a user in the Microsoft forums. It is the most voted answer

Thanks for the help.
