### ISSUE TITLE
Float vs Double

### ISSUE THREAD

**Issue by StevenGann** [ChrisDill/Raylib-cs#41]
I find that, when using Raylib-CS, I do a lot of casting between 32-bit float and 64-bit double.

In most applications on modern PCs, there's no reason to use 32-bit float instead of 64-bit double, since the execution time remains the same and you're only sacrificing precision. The big exception si if you need 32 bits for something, like some bit-shifting voodoo or micro-optimizations, but even then those aren't common or even good practice in .NET.

For Raylib itself, 32-bit float is great for cross-platform compatibility reasons, but for Raylib-CS would it be reasonable to substitute double for float in most cases, especially in Vector2 and Vector3?

**Comment by ChrisDill** [comment]
I am not sure if changing them to double would cause issues with pinvoke functions converting between the types.  It might work as expected but you should test with some of the Vector2 and Vector3 pinvoke functions to be sure.

**Comment by StevenGann** [comment]
Alright. I'll give it a whack and see if it works.
