### ISSUE TITLE
Raylib.Raylib.DrawTriangleStrip does not exist

### ISSUE THREAD

**Issue by Shadowblitz16** [ChrisDill/Raylib-cs#42]
this doesn't work due to DrawTriangleStrip not being implemented. 

```cs
        public static void Line(bool fill, uint col, params float[] points)
        {
            if ((points.Length % 2) != 0)
            {
                Console.WriteLine("Cannot draw without multipule of two points");
                return;
            }

            Vector2[] points2 = new Vector2[points.Length / 2];
            for (var i=0; i< points.Length; i+=2)
            {
                points2[i/2] = new Vector2(points[i+0], points[i+1]);
            }

            Col(col);

            if (fill) Raylib.Raylib.DrawTriangleFan  (points2, points2.Length, _col);
            else      Raylib.Raylib.DrawTriangleStrip(points2, points2.Length, _col);       
        }
```

**Comment by ChrisDill** [comment]
Not sure what version that was added. What version of raylib are you using and does it have that function?

The bindings are being updated on the dev branch to raylib 3.0. You can see that function [here](https://github.com/ChrisDill/Raylib-cs/blob/d78ee2493bf85c0f531129adebcdd280d9648b0a/Raylib-cs/Raylib.cs#L1934).

The dev branch has had some breaking changes and is not yet ready for use. Although you can try to use it as reference to add any functions you need in the meantime.

Hope this helps!

**Comment by Shadowblitz16** [comment]
I just downloaded the dll like a week ago so it should be up to date

Its good to know these are being added
I can wait until then.
