### ISSUE TITLE
NuGet package does not work in most configurations

### ISSUE THREAD

**Issue by rishavs** [ChrisDill/Raylib-cs#43]
I am trying to use Raylib-cs with fsharp on dotnet 3.1.

I am able to install the lib on a console app using `dotnet add Raylib-cs`
But now in my code doing
`open Raylib`
gives me the error `The namespace or module 'Raylib' is not defined.`

**Comment by ChrisDill** [comment]
I have not used fsharp so I cannot help there I am afraid. There are bindings for it here https://github.com/dallinbeutler/RaylibFS although I think it would need to be updated.

**Comment by rishavs** [comment]
I quickly testing this in c# and I am getting the same issue.

I started by creating a new C# console app and then added Raylib-cs to it. However in the code, it is not recognising raylib-cs
```
PS C:\Users\risharan\DevSpace\fsharp\test> dotnet new console                                                                                                                                                                                         The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\Users\risharan\DevSpace\fsharp\test\test.csproj...
  Restore completed in 119.24 ms for C:\Users\risharan\DevSpace\fsharp\test\test.csproj.

Restore succeeded.

PS C:\Users\risharan\DevSpace\fsharp\test> dotnet add package Raylib-cs                                                                                                                                                                                 Writing C:\Users\risharan\AppData\Local\Temp\tmpD0D6.tmp
info : Adding PackageReference for package 'Raylib-cs' into project 'C:\Users\risharan\DevSpace\fsharp\test\test.csproj'.
info : Restoring packages for C:\Users\risharan\DevSpace\fsharp\test\test.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/raylib-cs/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/raylib-cs/index.json 908ms
info : Package 'Raylib-cs' is compatible with all the specified frameworks in project 'C:\Users\risharan\DevSpace\fsharp\test\test.csproj'.
info : PackageReference for package 'Raylib-cs' version '1.4.0' added to file 'C:\Users\risharan\DevSpace\fsharp\test\test.csproj'.
info : Committing restore...
info : Generating MSBuild file C:\Users\risharan\DevSpace\fsharp\test\obj\test.csproj.nuget.g.targets.
info : Writing assets file to disk. Path: C:\Users\risharan\DevSpace\fsharp\test\obj\project.assets.json
log  : Restore completed in 2.55 sec for C:\Users\risharan\DevSpace\fsharp\test\test.csproj.
```

![image](https://user-images.githubusercontent.com/1210239/75089288-44b1d700-557d-11ea-9842-18102ad04d87.png)

**Comment by ChrisDill** [comment]
You should copy the bindings into your project directly instead of adding via the package. The package is unlisted and out of date. I had issues getting it to work. I may revisit it although I have been making breaking changes on the dev branch and it is not a priority at this time.

**Comment by rishavs** [comment]
Thanks. Thta makes sense.
I have edited the title of the issue so that it refers to updating the lib on dotnet package repo.

**Comment by ChrisDill** [comment]
The point of having it be a package is to make it easy for people to install and use so I would want it to include the native libraries too although I am not sure how it should be done. The dev branch is nearly ready to merge into master so I will work on that and take another look at this after.

**Comment by rishavs** [comment]
Hey Chris, I know you will have 3.0 as a priority but have you a timeline planned for this fix?

**Comment by ChrisDill** [comment]
I am not sure. There are different ways I could package it and I have not found a clear guide for nuget packages that use native libraries. I have tried dotnet pack and that produces a package for Raylib-cs.dll but I am stuck on figuring out how to add the native libraries so they are included and also are copied to the output directory based on the platform being used.

**Comment by ChrisDill** [comment]
Update. Taking another look to see if there was something I missed. Looks like there is a open issue abou usingt native libraries in nuget packages [here](https://github.com/NuGet/Home/issues/8623).

**Comment by 9ParsonsB** [comment]
Good news! We have just released a NuGet package targeting netstd2.0 (which should support Framework 4.7.2) & Core 3.1

So far we have tested it with the examples and with Github Actions, but please feel free to open new issues if there are problems with the package.

https://www.nuget.org/packages/Raylib-cs
`dotnet add package Raylib-cs`

**Comment by 9ParsonsB** [comment]
Seems like the current solution does not work for netfx under certain conditions. Refer to #3 of [this NuGet issue ](https://github.com/NuGet/Home/issues/6645) and [this comment](https://github.com/NuGet/Home/issues/6645#issuecomment-383639802)

Current options seem to be:
1. Add a target file (which means writing a target for each arch & platform we want to support)
2. rename the `runtime` folder to `libs` - this is documented to cause issues/warnings with MSBuild and I'd rather not do something hacky just for netfx

**Comment by ChrisDill** [comment]
@9ParsonsB I say we should look into the target files. I agree that renaming the folder to libs is hacky and sounds like it will cause more problems. The nuget package should be able to be built using dotnet pack with no other steps needed. If netfx can not work with that then we won't be able to support it.

**Comment by ChrisDill** [comment]
To make it clear on the runtimes we are currently supporting. The libraries we include for these runtimes are taken from the official raylib release:

- linux-x64
- linux-x86
- osx-x64
- win-x64
- win-x86

It is possible that linux-x86 and win-x86 support is dropped in the future as I do not use them myself and there is a extra cost in having to support/test them. Currently they are the least tested part because of this.

**Comment by 9ParsonsB** [comment]
After some more investigations, I have another approach for packaging native libraries after reviewing this: https://github.com/NuGet/Home/issues/8623 (now using `Content` rather than `Reference` in the `.targets` file)

I will push a new package version now and hope someone can test it for me [join us on discord!](https://discord.gg/VkzNHUE)

**Comment by Shadowblitz16** [comment]
does this use 64 bit binaries? I keep getting this..
![image](https://user-images.githubusercontent.com/2453707/81512131-0a7de900-92d3-11ea-958b-4da534898abf.png)
I downloaded the latest raylib native library and both 32 and 64 bit doesn't seem to work

**Comment by ChrisDill** [comment]
@Shadowblitz16 The latest nuget package currently includes the x64 and x86 libraries. Check that you are using the latest nuget release. You should not need to download the latest raylib library yourself to use the nuget package.

**Comment by horseyhorsey** [comment]
I get the incorrect format when trying to run `win-x86`, `x64` is fine though.

I was running from fork before but have just started to use the nuget.

**Comment by Shadowblitz16** [comment]
@ChrisDill the nuget package doesn't even install the C# bindings for me
I am using a .net framework 4.6

**Comment by Shadowblitz16** [comment]
@ChrisDill it doesn't work
![image](https://user-images.githubusercontent.com/2453707/83935737-214c1a00-a771-11ea-894d-c90d70b95166.png)
this is a blank console app targeted at .net framework 4.7.2

**Comment by horseyhorsey** [comment]
Set to x64.

Please set x86 and report that doesn't work.

**Comment by Shadowblitz16** [comment]
nope that doesn't work either
![image](https://user-images.githubusercontent.com/2453707/83981165-5458ef80-a8d0-11ea-8755-fa537bc7ca42.png)

**Comment by 9ParsonsB** [comment]
@Shadowblitz16 Are you targeting .Net Framework or .Net Core? 

.Net Framework doesn't handle cross-platform native libraries that well - in this case you will need to copy the native raylib dll into your output directory. 

In any case, you will probably have better luck by only building x64. I know AnyCPU is broken. not sure about x86.

I am currently testing a fix for this (see pre-release NuGet packages).
