### ISSUE TITLE
Raygui

### ISSUE THREAD

**Issue by horseyhorsey** [ChrisDill/Raylib-cs#46]
Hi
How do we get setup to use the bindings for RayGUI?

Missing a binary for raygui.dll?

**Comment by Shadowblitz16** [comment]
I would like to know this as well

**Comment by ChrisDill** [comment]
Initially raygui tried to load bindings from raylib but this required a custom build of raylib to include it as it is not built into raylib by default. This caused issues so I changed it to look for its own library raygui instead so on windows that would be raygui.dll etc.

There is a similar issue on raygui [here](https://github.com/raysan5/raygui/issues/75) with more details. I will look into improving the documentation to make this clearer to new users.
