### ISSUE TITLE
IsWindowMinimized() never runs

### ISSUE THREAD

**Issue by matej-zajacik** [ChrisDill/Raylib-cs#47]
`Raylib.IsWindowMinimized()` in my main loop never returns true, no matter what I do with the window (minimizing, switching to another window to have it lose focus, etc.).

Perhaps I'm misunderstanding something. How am I supposed to handle losing focus? I'd like to pause the simulation while out of focus for obvious reasons.

Thank you!

(I'm using the 3.0 version.)

**Comment by ChrisDill** [comment]
I just tested this in C# and in C and I get the same behavior. When the app is minimized everything else is paused so IsWindowMinimized will never be called until you reopen the window but then it will return false.

**Comment by ChrisDill** [comment]
Closing as this is not a issue specific to the bindings. I suggest opening a issue on the [parent repo](https://github.com/raysan5/raylib) instead.
