### ISSUE TITLE
Strange issue with RenderTexture

### ISSUE THREAD

**Issue by brandc87** [ChrisDill/Raylib-cs#52]
Hey. I'm just starting with Raylib and the C# Binding and seem to be having an issue with Render Textures.

I'm on a macOS 10.15.4 application is .NET Core 3.1

I create a texture the same size as the screen based on the examples when I draw it the size is off and if I move the window the my second monitor it zooms right into the bottom left corner.

```
            TemporaryA = Raylib.LoadRenderTexture(1024, 768);

             BeginTextureMode(EngineBuffers.TemporaryA);
             ClearBackground(Color.RED);
                
             //DrawTextureEx(Texture, position, rotation, scale, Fade(color, opacity));
                
             EndTextureMode();

             DrawTextureRec(EngineBuffers.TemporaryA.texture, new Rectangle(0, 0, 1024, -768), new Vector2(0, 0), Color.WHITE);
```

Will result in drawing:

<img width="1043" alt="Screenshot 2020-05-10 at 17 33 46" src="https://user-images.githubusercontent.com/11300674/81505030-977d6e00-92e4-11ea-889c-ceab830968dc.png">

When moving the game window to the second monitor when using a render texture (it's fine if I don't use any render textures):

![Screenshot 2020-05-10 at 17 34 02](https://user-images.githubusercontent.com/11300674/81505044-a49a5d00-92e4-11ea-9324-6f975653cbcf.png)

**Comment by brandc87** [comment]
On further investigation it seems related to [this issue](https://github.com/raysan5/raylib/issues/1086)

**Comment by ChrisDill** [comment]
@brandc87 I remember seeing a issue like this on [discord](https://discord.com/invite/VkzNHUE) so I suggest discussing it there. It does not seem to be to do with the bindings themselves.

**Comment by brandc87** [comment]
@ChrisDill thanks I've jumped on discord and it seems there is a work around which requires a new call to the GetWindowDPI function I'll get playing with that :)
