### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by ChrisDill** [ChrisDill/Raylib-cs#56]
Discussion on the state of documentation for this library.

## Code comments.

Using the same comments with the same style as raylib. One idea is to change them to the xmldoc style which can be used to generate external documentation. Unsure if this should be done but worth looking into.

## Tech notes

Documenting api differences to make it easier for people new to raylib. Could move details like this into a seperate wiki page or file if needed. For example, a guide on how to handle/access IntPtr variables since Raylib-cs uses these in structs and functions.

**Comment by CastimierDev** [comment]
I would like to help, where should I start?

**Comment by ChrisDill** [comment]
@CastimierDev I could use help with the wiki. Not quite sure how best to structure it. The goal is to point people to it to
answer common questions on the [discord](https://discord.gg/raylib).

Let me know what suggestions or ideas you have on this. Thanks!

**Comment by CastimierDev** [comment]
Perhaps we could add a short documentation about every subject and show a snippit where in it get's used.
For example working with files and audio

**Comment by 9ParsonsB** [comment]
Converting some of the commenting into `/// <summary>`  tags would help with IDE quick info
