### ISSUE TITLE
Titlebar color doesn't match system theme (macOS)

### ISSUE THREAD

**Issue by DanielGoldenberg0** [ChrisDill/Raylib-cs#57]
Unlike in the C version of raylib which does this automatically, the c#/dotnet version of raylib does not automatically set the window titlebar color to fit the system theme. Instead, it's stuck on the light theme

**Comment by ChrisDill** [comment]
The bindings call into raylib to create the window so I don't see why there would be a C# issue as it should be created the same way. I do not have access to macOS so I cannot test this myself. At a guess maybe there is a difference in the raylib versions.

**Comment by DanielGoldenberg0** [comment]
@ChrisDill Well then I am guessing that it may be a .NET Core related thing
