### ISSUE TITLE
I cannot use it with an OpenGL 2.1 PC

### ISSUE THREAD

**Issue by pupiraresdi** [ChrisDill/Raylib-cs#58]
The raylib.dll is only available as the OpenGL 3.3 version when you download raylib-msvc15 so i cant use it.

**Comment by ChrisDill** [comment]
@pupiraresdi This is because raylib has a variety of config options to compile with. I looked into custom builds but there are many configurations and I don't think I can support that. For OpenGL 2.1 you need to do a manual install with a custom version of raylib built for it.

**Comment by pupiraresdi** [comment]
Can you help me on a manual install, i use windows, raylib has an option to compile with OpenGL 2.1 but it doesnt compile a dll

**Comment by pupiraresdi** [comment]
I don't know how to compile it into an msvc version

**Comment by pupiraresdi** [comment]
@ChrisDill i don't know how to compile raylib into an msvc version

**Comment by ChrisDill** [comment]
@pupiraresdi Look at the msvc guide on the [raylib wiki](https://github.com/raysan5/raylib/wiki/Create-Visual-Studio-Project) for help compiling using msvc. There are built in projects for VS2017 you can use for building raylib which you should be able to re target to use OpenGL 2.1. 

For other questions about compiling raylib, I recommend opening a raylib [issue](https://github.com/raysan5/raylib/issues) or asking in the raylib [discord](https://discord.gg/VkzNHUE).
