### ISSUE TITLE
linux-arm build for Raspian desktop...

### ISSUE THREAD

**Issue by horseyhorsey** [ChrisDill/Raylib-cs#59]
Is this possible? I am trying to build for RASPI at the moment but it is a PITA tbh, hopefully get there soon.

**Comment by ChrisDill** [comment]
@horseyhorsey Raylib-cs uses the libraries in the official releases of raylib. If you need a custom version you need to build raylib yourself. Here is a [guide](https://github.com/raysan5/raylib/wiki/Working-on-Raspberry-Pi) on building for the raspberry pi from the raylib wiki.

**Comment by horseyhorsey** [comment]
Thanks Chris. I have had issues building / following that guide and some of the examples. If successful will be sure to try.
