### ISSUE TITLE
Unable to load textures

### ISSUE THREAD

**Issue by Giorgio54** [ChrisDill/Raylib-cs#61]
I'm trying to load a texture and it gives me an error saying: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt".
I also tried the examples and I get no error but in the console it says "WARNING: [resources/texture.png] failed to load" and the texture doesn't show, fonts, 3d object, ... works fine, it's just textures

**Comment by ChrisDill** [comment]
Make sure you call `LoadTexture` after `InitWindow` as that sets up the opengl context which is needed when loading textures.
The examples working directory must be set to the root of the examples repo although I am considering changing how that works.

**Comment by ChrisDill** [comment]
@Giorgio54 Update on the examples. I have now merged the resources folders into one to make it easier to setup and load them correctly.

**Comment by bayganik** [comment]
Wow, this was a great help!! Going crazy trying to figure out the access violation.

**Comment by Grave18** [comment]
my headache is gone too)

**Comment by PythonCodeingKing** [comment]
Yes! Same problem for me too, although it gave me a segfault. It was great figuring this out. Thanks!

**Comment by 10aded** [comment]
I was getting  a segfault when trying to call `LoadFontFromMemory`, my problem is now gone too!
