### ISSUE TITLE
Raylib 3.1.6 crashes upon loading obj file

### ISSUE THREAD

**Issue by Soup-64** [ChrisDill/Raylib-cs#65]
when loading in an obj file, the program crashes without warning and without any sort of error messages as shown below:
![image](https://user-images.githubusercontent.com/43444191/102397647-243f8700-3fac-11eb-838c-5a4ad8f90a03.png)
The program stops right after raylib outputs that it loaded obj data successfully. The model in question also loads fine within other applications, like blender, and the program also runs fine if the models aren't loaded in at all.

**Comment by 9ParsonsB** [comment]
@Soup-64 Did you figure out this issue?

**Comment by RonenNess** [comment]
I'm having the exact same issue, but I tried changing obj to glb and it didn't help.
Loading models under certain conditions seems to cause random crashes.

Anyone got a solution for this?
