### ISSUE TITLE
The Fade function does not exist in Raylib.cs

### ISSUE THREAD

**Issue by Ambez05** [ChrisDill/Raylib-cs#68]
I expect this code is missing in the Raylib.cs file

        [DllImport(nativeLibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern Color Fade(Color color, float alpha);

**Comment by ChrisDill** [comment]
I recently updated the bindings to 3.5.0 and there have been a lot of changes.
In this case, the Fade function has been renamed to ColorAlpha.
```csharp
// Returns color with alpha applied, alpha goes from 0.0f to 1.0f
[DllImport(nativeLibName, CallingConvention = CallingConvention.Cdecl)]
public static extern Color ColorAlpha(Color color, float alpha);
```

**Comment by raysan5** [comment]
@ChrisDill I think I kept the `Fade()` function... mmmh... did I remove it?

**Comment by ChrisDill** [comment]
> [textures] RENAMED: Fade() to ColorAlpha(), added #define for compatibility

In the source code the define is commented out.
```c
//#define Fade(c, a)  ColorAlpha(c, a)
```
However both Fade and ColorAlpha functions can be found in textures.c and they both do the same thing.

@Ambez05 If it helps I can add a compatibility function that calls ColorAlpha.
```csharp
// Returns color with alpha applied, alpha goes from 0.0f to 1.0f
// NOTE: Added for compatability with previous versions
public static Color Fade(Color color, float alpha) => ColorAlpha(color, alpha);
```
