### ISSUE TITLE
Codepoints above 127 not rendering on Windows

### ISSUE THREAD

**Issue by krank** [ChrisDill/Raylib-cs#69]
DrawText as implemented in Raylib-cs only supports codepoints up to 127 in Windows – all characters above that gets rendered as "?". This is kind of annoying, as I'm a swedish programming teacher, and we have a few special extended ascii-characters; å, ä and ö are part of a lit of swedish words.

Things I've tried:
- DrawText and DrawTextEx. Same result.
- Loading different fonts, with or without explicit inclusion of codepoints up to 255. Same result.
- Getting the latest Raylib-cs from the github page. Same result as with the nuget package.
- Running the same code but in a virtual Debian machine. THIS WORKS, so issue seems to be in Windows.
- Asking a friend who's proficient in C/C++ to try using åäö using Raylib in C++. THIS WORKS, so the issue seems to be specific to Raylib-cs, even though it's just a wrapper?
- DrawTextCodepoint. THIS WORKS, which means that for some reason the issue is specific to the DrawText methods (and InitWindow). Raylib is supposed to be Unicode-capable, and this proves that at least in theory, it is.

Here's my simple test code (just writes out characters 0-255):
```
static void Main(string[] args)
{
  int font_size = 10;
  Raylib.InitWindow(800, font_size * 64, "åäö");
  while (!Raylib.WindowShouldClose())
  {
    Raylib.BeginDrawing();
    Raylib.ClearBackground(Color.BEIGE);
    for (int i = 0; i < 255; i++)
    {
      int col = i / 64;
      int x = col * 200;
      int y = (i % 64) * font_size;
      string text = i.ToString() + " | " + ((char)i).ToString();

      Raylib.DrawText(text, x, y, font_size, Color.BLACK);
    }
    Raylib.EndDrawing();
  }
}
```
It works fine in Debian, as stated, but in Windows columns 3 and 4 are filled with ?:s and the window titlebar is also just ???.

An nice fellow on StackOverflow, who definitely deems to know more than me about these kind of things, had this to say:

> The way the library imports DrawText is faulty; its default behavior "marshals" string values to fit a legacy character encoding, not necessarily UTF-8: github.com/ChrisDill/Raylib-cs/blob/… . (Specifying CharSet=Unicode probably won't help because the DrawText function doesn't use wide-character strings, but rather ordinary char* pointers interpreted as UTF-8.)

([Peter O](https://stackoverflow.com/questions/65716686/making-raylib-cs-work-with-extended-ascii-unicode-above-128-in-windows?noredirect=1#comment116192333_65716686))

**Comment by 9ParsonsB** [comment]
Hi, thanks for using raylib-cs & bringing this to our attention! Very sorry for this oversight on our part, both me and @ChrisDill use Linux and are English-only speakers. We'll get on a fix asap.

**Comment by ChrisDill** [comment]
@9ParsonsB @krank I have found 2 possible fixes for the issue with UTF8 strings. Both work on windows for me.

1. Using `[MarshalAs(UnmanagedType.LPUTF8Str)]` to marshal strings as UTF8.
```csharp
public class TextBug1
{
    // Initialize window and OpenGL context
    [DllImport(Raylib.nativeLibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void InitWindow(int width, int height, [MarshalAs(UnmanagedType.LPUTF8Str)] string title);

    // Initialize window and OpenGL context
    [DllImport(Raylib.nativeLibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawText([MarshalAs(UnmanagedType.LPUTF8Str)] string text, int posX, int posY, int fontSize, Color color);

    static void Main(string[] args)
    {
        int font_size = 10;
        InitWindow(800, font_size * 64, "åäö");
        while (!Raylib.WindowShouldClose())
        {
            Raylib.BeginDrawing();
            Raylib.ClearBackground(Color.BEIGE);
            for (int i = 0; i < 255; i++)
            {
                int col = i / 64;
                int x = col * 200;
                int y = (i % 64) * font_size;
                string text = i.ToString() + " | " + ((char)i).ToString();

                DrawText(text, x, y, font_size, Color.BLACK);
            }
            Raylib.EndDrawing();
        }
    }
}
```

2. Wrapping the functions and using custom utils to marshal them to UTF8 the same way used in SDL2-cs.
```csharp
public class TextBug2
{
    internal static int Utf8Size(string str)
    {
        Debug.Assert(str != null);
        return (str.Length * 4) + 1;
    }

    internal static unsafe byte* Utf8Encode(string str, byte* buffer, int bufferSize)
    {
        Debug.Assert(str != null);
        fixed (char* strPtr = str)
        {
            Encoding.UTF8.GetBytes(strPtr, str.Length + 1, buffer, bufferSize);
        }
        return buffer;
    }

    // Initialize window and OpenGL context
    [DllImport(Raylib.nativeLibName, EntryPoint = "InitWindow", CallingConvention = CallingConvention.Cdecl)]
    private static extern unsafe void INTERNAL_InitWindow(int width, int height, byte* title);
    public static unsafe void InitWindow(int width, int height, string title)
    {
        int utf8NameBufSize = Utf8Size(title);
        byte* utf8Name = stackalloc byte[utf8NameBufSize];
        INTERNAL_InitWindow(width, height, Utf8Encode(title, utf8Name, utf8NameBufSize));
    }

    // Initialize window and OpenGL context
    [DllImport(Raylib.nativeLibName, EntryPoint = "DrawText", CallingConvention = CallingConvention.Cdecl)]
    private static extern unsafe void INTERNAL_DrawText(byte* text, int posX, int posY, int fontSize, Color color);
    public static unsafe void DrawText(string text, int posX, int posY, int fontSize, Color color)
    {
        int utf8NameBufSize = Utf8Size(text);
        byte* utf8Name = stackalloc byte[utf8NameBufSize];
        INTERNAL_DrawText(Utf8Encode(text, utf8Name, utf8NameBufSize), posX, posY, fontSize, color);
    }

    static void Main(string[] args)
    {
        int font_size = 10;
        InitWindow(800, font_size * 64, "åäö");
        while (!Raylib.WindowShouldClose())
        {
            Raylib.BeginDrawing();
            Raylib.ClearBackground(Color.BEIGE);
            for (int i = 0; i < 255; i++)
            {
                int col = i / 64;
                int x = col * 200;
                int y = (i % 64) * font_size;
                string text = i.ToString() + " | " + ((char)i).ToString();

                DrawText(text, x, y, font_size, Color.BLACK);
            }
            Raylib.EndDrawing();
        }
    }
}
```

**Comment by krank** [comment]
Thanks, @ChrisDill, can confirm both workarounds work here as well! I'll pass the first one on to my students immediately.

Very grateful for fast & helpful response; I'll be using this as an example in the classroom on how git/github, open source and issue tracking is supposed to work =)

**Comment by 15leesan** [comment]
I'm trying to display the pi character (π, U+03C0), but no matter what I do, all I get are underline characters.
Is there any way to draw it to the screen? It seems to be at least somewhat related to this issue.

I'm using the NuGet package for Raylib-cs 3.7.0.

**Comment by SWCreeperKing** [comment]
> I'm trying to display the pi character (π, U+03C0), but no matter what I do, all I get are underline characters.
> Is there any way to draw it to the screen? It seems to be at least somewhat related to this issue.
> 
> I'm using the NuGet package for Raylib-cs 3.7.0.

I believe its the same issue, I tried drawing text with a 127 unicode and it drew an underscore. I am also using Raylib-cs 3.7.0.

**Comment by prehistoriccraftman** [comment]
Too much complicated... i can't adapt that in my actual project.
We are in 2024, and there is still no way to write unicode characters.
I need to manage chinese and japan and some non latin european languages.

**Comment by 9ParsonsB** [comment]
@prehistoriccraftman If you have an issue, please show what you have tried, what is not working, the current version of raylib, raylib-cs, your platform, etc and we will do our best to help.
