### ISSUE TITLE
How to get working on Raspberry PI

### ISSUE THREAD

**Issue by davidscherf** [ChrisDill/Raylib-cs#73]
I have compiled Raylib and its examples, and have that working

I made a simple app in Dot Net Core 3.1, but when I run I get a dll not found exception

I cannot find a libraylib.so in the compiled Raylib

**Comment by ChrisDill** [comment]
@davidscherf Currently the Raylib-cs package does not include native libraries needed for the Raspberry PI.
You will need to build them manually and add them where they can be found in the search path of your app.

See https://github.com/raysan5/raylib/wiki/Working-on-Raspberry-Pi for details on building raylib.
