### ISSUE TITLE
Failed to load image!

### ISSUE THREAD

**Issue by zalnaRs** [ChrisDill/Raylib-cs#74]
So, i want to draw a simple 
![image](https://user-images.githubusercontent.com/53659756/109395661-d4772780-792d-11eb-9229-24f686c4c422.png)

And its saying this:
![image](https://user-images.githubusercontent.com/53659756/109395670-ee186f00-792d-11eb-8f8d-fffb6f43529d.png)

There is my code:
``
 using Raylib_cs;

 namespace test
 {
    class Program
    {
        static void Main(string[] args)
        {
            Raylib.InitWindow(800, 480, "Hello World");

            Image image = Raylib.LoadImage("assets/textures_image_loading.bmp");
            Texture2D texture = Raylib.LoadTextureFromImage(image);         

            Raylib.UnloadImage(image); 

            while (!Raylib.WindowShouldClose())
            {
                Raylib.BeginDrawing();
                Raylib.ClearBackground(Color.WHITE);

                Raylib.DrawTexture(texture, texture.width, texture.height, Color.WHITE);

                Raylib.DrawText("Hello, world!", 12, 12, 20, Color.BLACK);

                Raylib.EndDrawing();
            }

                 Raylib.CloseWindow();
               }
           }
        }
``

**Comment by ChrisDill** [comment]
@zalnaRs The .bmp format is not currently enabled in the raylib release. To use it you need to build raylib with `SUPPORT_FILEFORMAT_BMP` enabled.

**Comment by zalnaRs** [comment]
> @zalnaRs The .bmp format is not currently enabled in the raylib release. To use it you need to build raylib with `SUPPORT_FILEFORMAT_BMP` enabled.

I tried with png too!

**Comment by ChrisDill** [comment]
Then it most likely is failing to find the file. By default it loads from the output directory so try putting the assets folder in there and see if it finds it.

**Comment by zalnaRs** [comment]
> Then it most likely failing to find the file. By default it loads from the output directory so try putting the assets folder in there and see if it finds it.

Oh thanks I try it!

**Comment by zalnaRs** [comment]
Its works! :)
