### ISSUE TITLE
System.AccessViolationException on Raylib.EndDrawing() ?

### ISSUE THREAD

**Issue by sergiopolarbear** [ChrisDill/Raylib-cs#76]
I'm not sure if this is a bug within Raylib, Raylib-cs or if its in my code, [I asked on the raylib subreddit](https://www.reddit.com/r/raylib/comments/m54gns/manually_updating_screen/), but I haven't come to a solution.

My program doesn't use `while(!Raylib.WindowShouldClose())` for its main loop, because I need to update the screen on a function call rather than every frame. At the start of my program I run `Raylib.InitWindow(...)` and I have two methods that look like this:

```
public void Clear() 
{
    Raylib.BeginDrawing();
    Raylib.ClearBackground(...);
    Raylib.EndDrawing();
}

public void Draw() 
{
    Raylib.BeginDrawing();
    Raylib.DrawRectangle(...);
    Raylib.EndDrawing();
}
```
Again, I'm not sure if I'm doing this correctly, but it looks right to me.

I get this error message on `Raylib.EndDrawing()` in the `Clear()` method:

System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=Cannot evaluate the exception source
  StackTrace:Cannot evaluate the exception stack trace

**Comment by ChrisDill** [comment]
I don't see a issue with bindings here. I would need to know more about your program to find the issue. I made a test where I create a window and called Clear and Draw and it worked as expected.

**Comment by sergiopolarbear** [comment]
This is the class responsible for drawing to the screen:

```
using Raylib_cs;

namespace ChipSharp
{
    class DisplayHandler
    {
        public int Width { get; private set; }
        public int Height { get; private set; }
        private int resolutionMultiplier;
        private Color bgColor;
        private Color fgColor;

        private bool[,] grid;

        public DisplayHandler(int width, int height, int resolutionMultiplier, Color bgColor, Color fgColor)
        {
            this.Width = width;
            this.Height = height;
            this.resolutionMultiplier = resolutionMultiplier;
            this.bgColor = bgColor;
            this.fgColor = fgColor;

            grid = new bool[width, height];
        }

        public void Start()
        {
            Raylib.InitWindow(Width * resolutionMultiplier, Height * resolutionMultiplier, "Chip Sharp");
        }

        public void Clear()
        {
            Raylib.BeginDrawing();
            for(int x = 0; x < grid.GetLength(0); x++)
            {
                for (int y = 0; y < grid.GetLength(1); y++) { grid[x, y] = false; }
            }
            Raylib.ClearBackground(bgColor);
            Raylib.EndDrawing();
        }

        public bool FlipPixel(int a, int b)
        {
            Raylib.BeginDrawing();
            grid[a, b] = !grid[a, b];
            var x = a * resolutionMultiplier;
            var y = b * resolutionMultiplier;
            var color = grid[a, b] ? fgColor : bgColor;
            Raylib.DrawRectangle(x, y, resolutionMultiplier, resolutionMultiplier, color);
            Raylib.EndDrawing();
            return grid[a, b];
        }
    }
}
```

There's no more Raylib related code outside of this class, but these methods are called multiple times a second.

I just tested it again and it gave me the same error but in `Raylib.ClearBackground(bgColor);` instead...

In any case I don't think this is an issue with Raylib-cs so I don't mind closing the issue, but I'd appreciate any help if the code I provided reveals anything.

**Comment by ChrisDill** [comment]
Make sure InitWIndow is called before other drawing functions. I also suggest separating BeginDrawing and EndDrawing from the methods.

**Comment by sergiopolarbear** [comment]
Turns out I was accidentally calling the methods from a secondary thread and it was supposed to be from the main thread. Thanks for your help!
