### ISSUE TITLE
SetTracelogCallback impossible to format text

### ISSUE THREAD

**Issue by UC101** [ChrisDill/Raylib-cs#79]
This makes it impossible to format text passed by a TracelogCallback event. 
TracelogCallback takes a LogType, String and IntPtr. This is incompatible with C#'s built-in string formatting system. This means all the data that should be formatted into a string is treated as an unsafe blob. 

Currently Raylib-cs implements TextFormat as a function which takes in a string and returns the same string, perhaps this could be changed to allow passing a string and intptr in order to handle the C-style formatting required by TracelogCallback?

**Comment by ChrisDill** [comment]
I am aware of the issue. Another user found a separate workaround to format the text but it was platform dependent. I have tried to fix TextFormat but I have not yet got it to work.

**Comment by ChrisDill** [comment]
Custom logging has been improved in Raylib-cs 4.0.0 and uses specific native functions to handle the C-style formatting.
