### ISSUE TITLE
Doesn't seem to be a way to get string width and height based on font used

### ISSUE THREAD

**Issue by Shadowblitz16** [ChrisDill/Raylib-cs#80]
There doesn't seem to be a way to get a string's width and height in pixels based on the font used.
```
//MeasureText takes int not Font
var x = rect.X + (rect.W / 2) + Raylib.MeasureText(text, _font) / 2;

//Doesn't seem to be a way to get the height of it at all
var y = rect.Y + (rect.H / 2) + Raylib.?(text, _font) / 2;
```

**Comment by Shadowblitz16** [comment]
looks like there is Raylib.MeasureTextEx but why does Raylib.MeasureText take a int for a font?

**Comment by ChrisDill** [comment]
Both functions match raylib. MeasureText is there for the default font.
Not sure why fontSize is a int as it gets casted to a float when it calls MeasureTextEx internally.

**Comment by Shadowblitz16** [comment]
oh I see odd
