### ISSUE TITLE
Fix IntPtr returns and parameters so they return managed memory

### ISSUE THREAD

**Issue by Shadowblitz16** [ChrisDill/Raylib-cs#81]
The current method returns a IntPtr..
```
        public Color[] Lock()
        {
            var image = Raylib.GetTextureData(_texture);
            var colors = Raylib.LoadImageColors(image); //returns IntPtr
            return colors;
        }
```

Can you move these type of methods to return and take in managed memory?
If having IntPtr is necessary you could add it as a field or get property to the managed structs.

Its just hard to know what your doing if you don't know marshaling.

**Comment by ChrisDill** [comment]
There are different ways of handling the native memory used by raylib. I don't want the library to only allow certain ways of using it. For example marshaling adds a cost to copying memory across. I would rather the user decide what approach is best.

I am considering extensions for creating span types as it is a common issue people run into.

**Comment by Shadowblitz16** [comment]
you should make a overload for the function

**Comment by ChrisDill** [comment]
Like I said, I would rather the user decide what approach is best. There is no one way that the library should handle it.
