### ISSUE TITLE
NuGet package doesn't seem to be published yet

### ISSUE THREAD

**Issue by benbeshara** [ChrisDill/Raylib-cs#84]
Running the command `dotnet add package Raylib-cs --version 3.7.0` from the readme produces the following error:
```shell
error: NU1102: Unable to find package Raylib-cs with version (>= 3.7.0)
error:   - Found 20 version(s) in nuget.org [ Nearest version: 3.5.0 ]
```
Checking the NuGet API only shows up to 3.5:
```json
{
  "versions": [
    "1.0.0",
    "1.0.1",
    "1.0.2",
    "1.3.0",
    "1.4.0",
    "3.0.0-pre1",
    "3.0.0-pre2",
    "3.0.0",
    "3.0.1",
    "3.0.2",
    "3.1.0",
    "3.1.1",
    "3.1.2",
    "3.1.3",
    "3.1.4",
    "3.1.5",
    "3.1.6",
    "3.1.8-pre1",
    "3.1.8-pre2",
    "3.5.0"
  ]
}
```
I'm using dotnet 5.0.202

**Comment by 9ParsonsB** [comment]
@ChrisDill Should be doing this as part of actions, no? 

Only thing missing is the native lib in `runtimes/` folder (maybe write a shell script to get it?), then actions should be able to create the nupkg and upload

**Comment by ChrisDill** [comment]
@benbeshara I have now upload the package for 3.7.0.

@9ParsonsB I agree we should make the process more automated though I am unsure on how to do it. I want to be careful I don't mess up the versioning. Not sure if I should stick to matching the version of raylib...
