### ISSUE TITLE
Windows10  Gestures not working as expected. GESTURE_TAP is not detected until second tap.

### ISSUE THREAD

**Issue by Hshore** [ChrisDill/Raylib-cs#88]
GESTURE_TAP does not get detected on first tap of screen, the first touch only moves the mouse position and does not trigger a tap gesture.

I am not sure if this is a Raylib-cs bindings issue or a Raylib issue or even a windows issue.
I am running a .NET core 3.1 console app project but I just cant get the touchscreen gesture tap to work properly.

Despite this I am having a blast using Raylib with C# so thanks for all your hard work making this.

**Comment by ChrisDill** [comment]
Doesn't look like a Raylib-cs issue since raylib manages storing the gestures. GESTURE_TAP works for me with the mouse on desktop so it is likely a platform related issue.
