### ISSUE TITLE
Enum KeyBoardKey has duplicate value

### ISSUE THREAD

**Issue by GoldenQubicle** [ChrisDill/Raylib-cs#89]
Pretty self explanatory. Enum member KEY_R and KEY_MENU have to same value. 

![image](https://user-images.githubusercontent.com/21037627/131226205-4d57b7ea-c7d9-4a1b-8bde-c59a1dd935b3.png)

Bit annoying when - completely hypothetical - one wants to use R for reset and have to check for the menu key.  Not a big deal though, loving these bindings. Keep up the great work.

**Comment by ChrisDill** [comment]
KEY_MENU is part of the android key buttons that were added into KeyboardKey enum. For the menu key on the keyboard you can use KEY_KB_MENU.
