### ISSUE TITLE
Fix MarshallAs issue with raylib structs

### ISSUE THREAD

**Issue by ChrisDill** [ChrisDill/Raylib-cs#9]
There are issues getting unmanaged arrays with a fixed size to work in C#. I have had errors with using LoadShader throwing error "Method's type signature is not PInvoke compatible".

I am not sure what I am doing wrong. 
Here are the structs using MarshallAs currently and the array from C.
- Mesh ```unsigned int vboId[7];```
- Shader ```int locs[MAX_SHADER_LOCATIONS];```
- Material ```MaterialMap maps[MAX_MATERIAL_MAPS];```

**Comment by raysan5** [comment]
Maybe those arrays should be defined as just pointers and allocated by `LoadMesh()`, `LoadShader()`, `LoadMaterial()`?

**Comment by ChrisDill** [comment]
I had similar issue with Font and CharInfo that I solved with IntPtr. However they were pointers not fixed arrays. 

I tried changing the Shader to use IntPt but it crashes with a "System.AccessViolationException".

This is the Marshall code im using for the Shader. Tested with ```LoadShader```.
```
[MarshalAs(UnmanagedType.ByValArray, SizeConst = Raylib.MAX_SHADER_LOCATIONS)]
public int[] locs;
```
Where Raylib.MAX_SHADER_LOCATIONS is a constant equal to 32.

**Comment by ChrisDill** [comment]
Update, after looking at the different options it seems you cannot Marshall fixed size arrays without using the fixed keyword. This requires this library and any that use it to be compiled as unsafe. For now it will use this instead.

I will keep this issue open for now in case a better solution is found in the future.

**Comment by FireflyX** [comment]
@ChrisDill Why not just compile the library with unsafe?

With .Net Core I believe you can use Span<T> and its variants to handle this issue without `fixed`.  But don't quote me on that.

**Comment by ChrisDill** [comment]
At the moment it is compiled as unsafe. I may keep it like that. I have tested using Span properties that use the IntPtr for mesh vertices, texcoords etc. Not sure if I prefer that.
